### ISSUE TITLE
CT cannot read property skaterState of undefined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#104]
```
energy-skate-park : fuzz : built : run
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'skaterState' of undefined
TypeError: Cannot read property 'skaterState' of undefined
    at Object.drag (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/energy-skate-park/build/phet/energy-skate-park_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1071:1598051)
    at t.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/energy-skate-park/build/phet/energy-skate-park_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1071:1593562)
    at t.drag (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/energy-skate-park/build/phet/energy-skate-park_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1071:417440)
    at _dragAction.i.parameters.name (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/energy-skate-park/build/phet/energy-skate-park_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1071:1354382)
    at i.value (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/energy-skate-park/build/phet/energy-skate-park_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1071:36512)
    at t.drag (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/energy-skate-park/build/phet/energy-skate-park_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1071:1355574)
    at t.pointerMove (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/energy-skate-park/build/phet/energy-skate-park_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1071:419127)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/energy-skate-park/build/phet/energy-skate-park_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1071:709703)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/energy-skate-park/build/phet/energy-skate-park_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1071:709395)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/energy-skate-park/build/phet/energy-skate-park_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1071:708863)
id: Bayes Chrome
Approximately 8/9/2019, 3:09:58 AM
energy-skate-park : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: model has no saved SkaterSamples to retrieve
Error: Assertion failed: model has no saved SkaterSamples to retrieve
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/assert/js/assert.js:22:13)
    at GraphsModel.getClosestSkaterSample (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/energy-skate-park/js/energy-skate-park/graphs/model/GraphsModel.js?:189:17)
    at Object.drag (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/energy-skate-park/js/energy-skate-park/graphs/view/EnergyPlot.js?:92:41)
    at DragListener.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/griddle/js/XYCursorPlot.js?:321:19)
    at DragListener.drag (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/scenery/js/listeners/PressListener.js?:401:12)
    at DragListener._dragAction.Action.parameters.name (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/scenery/js/listeners/DragListener.js?:194:36)
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/axon/js/Action.js?:244:20)
    at DragListener.drag (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/scenery/js/listeners/DragListener.js?:308:24)
    at DragListener.pointerMove (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/scenery/js/listeners/PressListener.js?:655:14)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/scenery/js/input/Input.js?:1797:27)
id: Bayes Chrome
Approximately 8/9/2019, 3:09:58 AM
energy-skate-park : phet-io-fuzz : require.js : load
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/assert/js/assert.js:22:13)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/tandem/js/Tandem.js?:115:21)
    at BooleanProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/tandem/js/PhetioObject.js?:298:19)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/tandem/js/PhetioObject.js?:131:12)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/axon/js/Property.js?:79:7)
    at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/axon/js/BooleanProperty.js?:47:7)
    at ToggleButtonModel.ButtonModel [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/sun/js/buttons/ButtonModel.js?:72:28)
    at new ToggleButtonModel (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/sun/js/buttons/ToggleButtonModel.js?:39:17)
    at ExpandCollapseButton.RectangularToggleButton [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/sun/js/buttons/RectangularToggleButton.js?:37:30)
    at new BooleanRectangularToggleButton (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/sun/js/buttons/BooleanRectangularToggleButton.js?:30:29)
id: Bayes Chrome
Approximately 8/9/2019, 3:09:58 AM
energy-skate-park : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/assert/js/assert.js:22:13)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/tandem/js/Tandem.js?:115:21)
    at BooleanProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/tandem/js/PhetioObject.js?:298:19)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/tandem/js/PhetioObject.js?:131:12)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/axon/js/Property.js?:79:7)
    at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/axon/js/BooleanProperty.js?:47:7)
    at ToggleButtonModel.ButtonModel [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/sun/js/buttons/ButtonModel.js?:72:28)
    at new ToggleButtonModel (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/sun/js/buttons/ToggleButtonModel.js?:39:17)
    at ExpandCollapseButton.RectangularToggleButton [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/sun/js/buttons/RectangularToggleButton.js?:37:30)
    at new BooleanRectangularToggleButton (https://bayes.colorado.edu/continuous-testing/snapshot-1565341798557/sun/js/buttons/BooleanRectangularToggleButton.js?:30:29)
id: Bayes Chrome
Approximately 8/9/2019, 3:09:58 AM
energy-skate-park : phet-io-tests : assert
9 out of 9 tests passed. 0 failed.

Approximately 8/9/2019, 3:09:58 AM
energy-skate-park : phet-io-tests : no-assert
9 out of 9 tests passed. 0 failed.

Approximately 8/9/2019, 3:09:58 AM
```

**Comment by jessegreenberg** [comment]
I haven't been to produce this locally yet but I think this is what we care about:
> model has no saved SkaterSamples to retrieve

**Comment by jessegreenberg** [comment]
It looks like the cursor is visible and draggable before any data is added to the graph. The cursor should remain invisible until data is added.

**Comment by jessegreenberg** [comment]
I think the issue may be related to this TODO:

>// TODO: Get the index of the position removed sample rather than assume they will be removed from oldest to newest?

points are removed from the dataseries without checking whether they have already been removed, and it is possible they have already been removed from the cursor drag end.

**Comment by jessegreenberg** [comment]
This is fixed with the above commits. There were a number of reasons this was happening (cursor remained visible when no data existed, calculation of plotted x-range was incorrect). I also found a memory leak that was resolved with these changes. Sim is fuzzing now locally with no error, this can finally be closed.

**Comment by jessegreenberg** [comment]
Something isn't quite right with dragging the cursor, it snaps back to the minimum x value.

**Comment by jessegreenberg** [comment]
This bit hard, but the behavior is finally working correctly and the sim is fuzzing without issue. Closing.
