### ISSUE TITLE
Tandem was required but not supplied

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#108]
```
energy-skate-park : phet-io-fuzz : require.js : load
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1565713001601/assert/js/assert.js:22:13)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1565713001601/tandem/js/Tandem.js?:115:21)
    at BooleanProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1565713001601/tandem/js/PhetioObject.js?:298:19)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1565713001601/tandem/js/PhetioObject.js?:131:12)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1565713001601/axon/js/Property.js?:79:7)
    at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1565713001601/axon/js/BooleanProperty.js?:47:7)
    at ToggleButtonModel.ButtonModel [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1565713001601/sun/js/buttons/ButtonModel.js?:72:28)
    at new ToggleButtonModel (https://bayes.colorado.edu/continuous-testing/snapshot-1565713001601/sun/js/buttons/ToggleButtonModel.js?:39:17)
    at ExpandCollapseButton.RectangularToggleButton [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1565713001601/sun/js/buttons/RectangularToggleButton.js?:37:30)
    at new BooleanRectangularToggleButton (https://bayes.colorado.edu/continuous-testing/snapshot-1565713001601/sun/js/buttons/BooleanRectangularToggleButton.js?:30:29)
id: Bayes Chrome
Approximately 8/13/2019, 10:16:41 AM
energy-skate-park : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1565713001601/assert/js/assert.js:22:13)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1565713001601/tandem/js/Tandem.js?:115:21)
    at BooleanProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1565713001601/tandem/js/PhetioObject.js?:298:19)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1565713001601/tandem/js/PhetioObject.js?:131:12)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1565713001601/axon/js/Property.js?:79:7)
    at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1565713001601/axon/js/BooleanProperty.js?:47:7)
    at ToggleButtonModel.ButtonModel [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1565713001601/sun/js/buttons/ButtonModel.js?:72:28)
    at new ToggleButtonModel (https://bayes.colorado.edu/continuous-testing/snapshot-1565713001601/sun/js/buttons/ToggleButtonModel.js?:39:17)
    at ExpandCollapseButton.RectangularToggleButton [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1565713001601/sun/js/buttons/RectangularToggleButton.js?:37:30)
    at new BooleanRectangularToggleButton (https://bayes.colorado.edu/continuous-testing/snapshot-1565713001601/sun/js/buttons/BooleanRectangularToggleButton.js?:30:29)
id: Bayes Chrome
Approximately 8/13/2019, 10:16:41 AM
```

**Comment by jessegreenberg** [comment]
This has since been fixed.
