### ISSUE TITLE
CT cannot read property 0 of undefined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#118]
```
energy-skate-park : fuzz : built-phet-io : run
Query: fuzz&memoryLimit=1000&phetioStandalone
Uncaught TypeError: Cannot read property '0' of undefined
TypeError: Cannot read property '0' of undefined
    at https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687-phet-io/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1069:79533
    at t.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687-phet-io/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1069:40794)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687-phet-io/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1069:79451)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687-phet-io/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1069:79025)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687-phet-io/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1069:1373521
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687-phet-io/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1069:31126)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687-phet-io/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1069:79647)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687-phet-io/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1069:79025)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687-phet-io/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1069:361752)
    at _.extend.startCallback (https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687-phet-io/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1069:1311556)
id: Bayes Chrome
Approximately 9/5/2019, 5:03:33 AM
energy-skate-park : phet-io-fuzz : require.js : load
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioType passed to Property must be specified. Tandem.phetioID: energySkatePark.introScreen.view.adapterProperty
Error: Assertion failed: phetioType passed to Property must be specified. Tandem.phetioID: energySkatePark.introScreen.view.adapterProperty
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687/assert/js/assert.js:22:13)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687/axon/js/Property.js?:84:84)
    at new PhysicalComboBox (https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687/energy-skate-park/js/energy-skate-park/common/view/PhysicalComboBox.js?:60:31)
    at new MassComboBox (https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687/energy-skate-park/js/energy-skate-park/common/view/MassComboBox.js?:36:7)
    at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687/energy-skate-park/js/energy-skate-park/intro/view/IntroScreenView.js?:38:25)
    at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687/energy-skate-park/js/energy-skate-park/intro/IntroScreen.js?:41:34)
    at IntroScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687/joist/js/Screen.js?:260:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687/joist/js/Sim.js?:805:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687/joist/js/Sim.js?:813:27
id: Bayes Chrome
Approximately 9/5/2019, 5:03:33 AM
energy-skate-park : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioType passed to Property must be specified. Tandem.phetioID: energySkatePark.introScreen.view.adapterProperty
Error: Assertion failed: phetioType passed to Property must be specified. Tandem.phetioID: energySkatePark.introScreen.view.adapterProperty
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687/assert/js/assert.js:22:13)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687/axon/js/Property.js?:84:84)
    at new PhysicalComboBox (https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687/energy-skate-park/js/energy-skate-park/common/view/PhysicalComboBox.js?:60:31)
    at new MassComboBox (https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687/energy-skate-park/js/energy-skate-park/common/view/MassComboBox.js?:36:7)
    at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687/energy-skate-park/js/energy-skate-park/intro/view/IntroScreenView.js?:38:25)
    at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687/energy-skate-park/js/energy-skate-park/intro/IntroScreen.js?:41:34)
    at IntroScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687/joist/js/Screen.js?:260:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687/joist/js/Sim.js?:805:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1567681413687/joist/js/Sim.js?:813:27
id: Bayes Chrome
Approximately 9/5/2019, 5:03:33 AM
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe fixed in the above
