### ISSUE TITLE
CT: iframe api failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#22]
```
energy-skate-park : phet-io-tests
6 out of 7 tests passed. 1 failed.
SimTests: energy-skate-park: iframe api failed:
No error should occur in setting state: Error: Cannot read property 'map' of undefined
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/js/tests/SimTests.js?bust=1538964251241:127:20)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/common/js/Client.js:300:81)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/common/js/Client.js:337:13)


Approximately 10/7/2018, 6:24:45 PM
energy-skate-park : phet-io-tests
6 out of 7 tests passed. 1 failed.
SimTests: energy-skate-park: iframe api failed:
No error should occur in setting state: Error: Cannot read property 'map' of undefined
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/js/tests/SimTests.js?bust=1538967921329:127:20)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/common/js/Client.js:300:81)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/common/js/Client.js:337:13)


Approximately 10/7/2018, 6:24:45 PM
energy-skate-park : phet-io-tests
6 out of 7 tests passed. 1 failed.
SimTests: energy-skate-park: iframe api failed:
No error should occur in setting state: Error: Cannot read property 'map' of undefined
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/js/tests/SimTests.js?bust=1538974764456:127:20)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/common/js/Client.js:300:81)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/common/js/Client.js:337:13)


Approximately 10/7/2018, 6:24:45 PM
energy-skate-park : phet-io-tests
6 out of 7 tests passed. 1 failed.
SimTests: energy-skate-park: iframe api failed:
No error should occur in setting state: Error: Cannot read property 'map' of undefined
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/js/tests/SimTests.js?bust=1538977315912:127:20)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/common/js/Client.js:300:81)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/common/js/Client.js:337:13)


Approximately 10/7/2018, 6:24:45 PM
energy-skate-park : phet-io-tests
6 out of 7 tests passed. 1 failed.
SimTests: energy-skate-park: iframe api failed:
No error should occur in setting state: Error: Cannot read property 'map' of undefined
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/js/tests/SimTests.js?bust=1538984075047:127:20)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/common/js/Client.js:300:81)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/common/js/Client.js:337:13)


Approximately 10/7/2018, 6:24:45 PM
energy-skate-park : phet-io-tests
6 out of 7 tests passed. 1 failed.
SimTests: energy-skate-park: iframe api failed:
No error should occur in setting state: Error: Cannot read property 'map' of undefined
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/js/tests/SimTests.js?bust=1538986921563:127:20)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/common/js/Client.js:300:81)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/common/js/Client.js:337:13)


Approximately 10/7/2018, 6:24:45 PM
energy-skate-park : phet-io-tests
6 out of 7 tests passed. 1 failed.
SimTests: energy-skate-park: iframe api failed:
No error should occur in setting state: Error: Cannot read property 'map' of undefined
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/js/tests/SimTests.js?bust=1538991300578:127:20)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/common/js/Client.js:300:81)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/common/js/Client.js:337:13)


Approximately 10/7/2018, 6:24:45 PM
energy-skate-park : phet-io-tests
6 out of 7 tests passed. 1 failed.
SimTests: energy-skate-park: iframe api failed:
No error should occur in setting state: Error: Cannot read property 'map' of undefined
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/js/tests/SimTests.js?bust=1539003200905:127:20)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/common/js/Client.js:300:81)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/common/js/Client.js:337:13)


Approximately 10/7/2018, 6:24:45 PM
energy-skate-park : phet-io-tests
6 out of 7 tests passed. 1 failed.
SimTests: energy-skate-park: iframe api failed:
No error should occur in setting state: Error: Cannot read property 'map' of undefined
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/js/tests/SimTests.js?bust=1539007379990:127:20)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/common/js/Client.js:300:81)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1538958285109/phet-io-wrappers/common/js/Client.js:337:13)


Approximately 10/7/2018, 6:24:45 PM
```

**Comment by chrisklus** [comment]
Looks like @samreid is responsible dev for energy skate park, passing assignment.

**Comment by jessegreenberg** [comment]
I have been making commits in this repo over the past few days, probably introduced by me. Ill take a look.

**Comment by jessegreenberg** [comment]
When running state wrapper, I see this for all screens:
![capture](https://user-images.githubusercontent.com/6396244/46969113-0819c580-d083-11e8-942a-5b894274e1a2.PNG)

**Comment by jessegreenberg** [comment]
```      assert && assertInstanceOf( energySkateParkModel, phet.energySkatePark.energySkateParkModel );```

That lower e on phet.energySkatePark.energySkateParkModel looks incorrect.

**Comment by jessegreenberg** [comment]
Fixed above. Now I am seeing something downstream.
> Assertion failed: controlPointTandemIDs should exist

**Comment by jessegreenberg** [comment]
@samreid or @zepumph could I please have some help with this issue? Why is ControlPointIO returning the phetioID in toStateObject? I am not sure why this isn't happening in energy-skate-park-basics.

**Comment by samreid** [comment]
My apologies for the long delay in getting to this issue.  When launching http://localhost/phet-io-wrappers/state/?sim=energy-skate-park I'm getting an issue that IOType is null on this line:

```js
instanceRemovedEmitter.emit2( phetioID, IOType.typeName );
```

Also, I'm hesitant to work too much on bugs affecting Energy Skate Park and Energy Skate Park: Basics before their codebases are aligned in https://github.com/phetsims/energy-skate-park/issues/6.

**Comment by samreid** [comment]
On hold until hearing from @jessegreenberg in #6

**Comment by jessegreenberg** [comment]
Since #6 is wrapped up I believe that this is no longer on hold. Removing my assignment but let me know if I can help with this.

**Comment by samreid** [comment]
Two points to identify for @jessegreenberg and other developers using tandem.  

* In Screen classes, use `tandem.createTandem('model')` and `tandem.createTandem('view')` instead of more specific strings
* When calling a super constructor, just pass through tandem instead of using `createTandem`

See the preceding commits for details.  Reassigned to @jessegreenberg to make sure he is aware of these points, or for discussion.  Also leaving self-assigned to continue searching for the root of the problem in this issue.

**Comment by samreid** [comment]
I could not understand why track/control point serialization was failing for the intro and friction screens.  I also realized that track/control point serialization are not necessary or desirable there (though uniform serialization of tracks in all screens may lead to a simpler implementation), so that is disabled in the prior commit.  Wrapper unit tests are passing on my local.  Closing for now and will keep an eye on Bayes CT in next business days.

**Comment by samreid** [comment]
Oops, reopening regarding https://github.com/phetsims/energy-skate-park/issues/22#issuecomment-445470260

**Comment by jessegreenberg** [comment]
Thanks for working on this @samreid, and understood with https://github.com/phetsims/energy-skate-park/issues/22#issuecomment-445470260, I will proceed with that moving forward.

With https://github.com/phetsims/energy-skate-park/issues/22#issuecomment-445472852, this issue can be reclosed.
