### ISSUE TITLE
CT Mismatched index, possible start/end mismatch

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#233]
```
energy-skate-park : phet-io-state-fuzz : require.js : run
Uncaught Error: Uncaught Error: Assertion failed: mismatched index, possible start/end mismatch
Error: Assertion failed: mismatched index, possible start/end mismatch
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/assert/js/assert.js?bust=1583747748367:22:13)
    at DataStream.end (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-io/js/dataStream.js:267:15)
    at PhetioCommandProcessor.phetioEndEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tandem/js/PhetioObject.js:421:30)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-io/js/phetioCommandProcessor.js:107:18
id: Bayes Chrome
Approximately 3/9/2020, 3:16:42 AM
energy-skate-park : phet-io-state-fuzz : require.js : run
Uncaught Error: Assertion failed: PhET-iO API error:
energySkatePark.introScreen.model.loopTrack.physicalProperty:  6. Any static, registered PhetioObject can never be deregistered.
Error: Assertion failed: PhET-iO API error:
energySkatePark.introScreen.model.loopTrack.physicalProperty:  6. Any static, registered PhetioObject can never be deregistered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/assert/js/assert.js?bust=1583747748367:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onPhetioObjectRemoved (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tandem/js/phetioAPIValidation.js:160:12)
    at PhetioEngine.phetioObjectRemoved (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-io/js/phetioEngine.js:492:25)
    at Object.removePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-io/js/phetioEngine.js:537:52)
    at Tandem.removePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tandem/js/Tandem.js:168:38)
    at BooleanProperty.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tandem/js/PhetioObject.js:557:19)
    at BooleanProperty.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/axon/js/Property.js:451:11)
    at BooleanProperty.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tandem/js/PhetioObject.js:199:20)
    at Track.disposeTrack (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/energy-skate-park/js/energy-skate-park/common/model/Track.js:191:29)
id: Bayes Chrome
Approximately 3/9/2020, 3:16:42 AM
energy-skate-park : phet-io-tests : assert
9 out of 9 tests passed. 0 failed.

Approximately 3/9/2020, 3:16:42 AM
energy-skate-park : phet-io-tests : no-assert
9 out of 9 tests passed. 0 failed.

Approximately 3/9/2020, 3:16:42 AM
```

**Comment by KatieWoe** [comment]
Possibly related?
```
energy-skate-park : phet-io-fuzz : require.js : load
https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/energy-skate-park/energy-skate-park_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID already registered: energySkatePark.introScreen.view.introScreenView.controlPanel.visibilityControls.text.visibleProperty
Error: Assertion failed: phetioID already registered: energySkatePark.introScreen.view.introScreenView.controlPanel.visibilityControls.text.visibleProperty
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/assert/js/assert.js:22:13)
    at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/phet-io/js/phetioEngine.js:380:34)
    at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/phet-io/js/phetioEngine.js:537:49)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/tandem/js/Tandem.js:144:38)
    at NodeProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/tandem/js/PhetioObject.js:355:17)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/tandem/js/PhetioObject.js:189:10)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/axon/js/Property.js:67:5)
    at new NodeProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/scenery/js/util/NodeProperty.js:37:5)
    at new NodeIO (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/scenery/js/nodes/NodeIO.js:26:29)
    at new TextIO (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/scenery/js/nodes/TextIO.js:29:5)
id: Bayes Chrome
Approximately 4/6/2020, 3:19:46 AM
energy-skate-park : phet-io-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/energy-skate-park/energy-skate-park_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID already registered: energySkatePark.introScreen.view.introScreenView.controlPanel.visibilityControls.text.visibleProperty
Error: Assertion failed: phetioID already registered: energySkatePark.introScreen.view.introScreenView.controlPanel.visibilityControls.text.visibleProperty
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/assert/js/assert.js:22:13)
    at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/phet-io/js/phetioEngine.js:380:34)
    at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/phet-io/js/phetioEngine.js:537:49)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/tandem/js/Tandem.js:144:38)
    at NodeProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/tandem/js/PhetioObject.js:355:17)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/tandem/js/PhetioObject.js:189:10)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/axon/js/Property.js:67:5)
    at new NodeProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/scenery/js/util/NodeProperty.js:37:5)
    at new NodeIO (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/scenery/js/nodes/NodeIO.js:26:29)
    at new TextIO (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/scenery/js/nodes/TextIO.js:29:5)
id: Bayes Chrome
Approximately 4/6/2020, 3:19:46 AM
energy-skate-park : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/phet-io-wrappers/state/?sim=energy-skate-park&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Assertion failed: PhET-iO API error:
energySkatePark.introScreen.model.loopTrack.physicalProperty:  6. Any static, registered PhetioObject can never be deregistered.
Error: Assertion failed: PhET-iO API error:
energySkatePark.introScreen.model.loopTrack.physicalProperty:  6. Any static, registered PhetioObject can never be deregistered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onPhetioObjectRemoved (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/tandem/js/phetioAPIValidation.js:161:12)
    at PhetioEngine.phetioObjectRemoved (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/phet-io/js/phetioEngine.js:493:25)
    at Object.removePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/phet-io/js/phetioEngine.js:538:52)
    at Tandem.removePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/tandem/js/Tandem.js:169:38)
    at BooleanProperty.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/tandem/js/PhetioObject.js:557:19)
    at BooleanProperty.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/axon/js/Property.js:451:11)
    at BooleanProperty.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/tandem/js/PhetioObject.js:199:20)
    at Track.disposeTrack (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/energy-skate-park/js/energy-skate-park/common/model/Track.js:188:29)
id: Bayes Chrome
Approximately 4/6/2020, 3:19:46 AM
energy-skate-park : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/phet-io-wrappers/state/?sim=energy-skate-park&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: mismatched index, possible start/end mismatch
Error: Assertion failed: mismatched index, possible start/end mismatch
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/assert/js/assert.js:22:13)
    at DataStream.end (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/phet-io/js/dataStream.js:267:15)
    at PhetioCommandProcessor.phetioEndEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/tandem/js/PhetioObject.js:421:30)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/phet-io/js/phetioCommandProcessor.js:109:18
id: Bayes Chrome
Approximately 4/6/2020, 3:19:46 AM
energy-skate-park : phet-io-tests : assert
https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/phet-io-wrappers/phet-io-wrappers-tests.html?sim=energy-skate-park&phetioDebug
9 out of 9 tests passed. 0 failed.

Approximately 4/6/2020, 3:19:46 AM
energy-skate-park : phet-io-tests : no-assert
https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/phet-io-wrappers/phet-io-wrappers-tests.html?sim=energy-skate-park
9 out of 9 tests passed. 0 failed.

Approximately 4/6/2020, 3:19:46 AM
energy-skate-park : xss-fuzz : load
https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/energy-skate-park/energy-skate-park_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Corner overlap on left edge
Error: Assertion failed: Corner overlap on left edge
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/assert/js/assert.js:22:13)
    at Function.Shape.roundedRectangleWithRadii (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/kite/js/Shape.js:2074:13)
    at createButtonShape (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/sun/js/buttons/RectangularButtonView.js:227:16)
    at ComboBoxButton.RectangularButtonView [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/sun/js/buttons/RectangularButtonView.js:138:28)
    at new RectangularPushButton (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/sun/js/buttons/RectangularPushButton.js:55:25)
    at new ComboBoxButton (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/sun/js/ComboBoxButton.js:129:5)
    at new ComboBox (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/sun/js/ComboBox.js:116:19)
    at new PhysicalComboBox (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/energy-skate-park/js/energy-skate-park/common/view/PhysicalComboBox.js:85:5)
    at new MassComboBox (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/energy-skate-park/js/energy-skate-park/common/view/MassComboBox.js:57:22)
    at new EnergySkateParkMassControls (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/energy-skate-park/js/energy-skate-park/common/view/EnergySkateParkMassControls.js:58:22)
id: Bayes Chrome
Approximately 4/6/2020, 3:19:46 AM
energy-skate-park : xss-fuzz : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/energy-skate-park/energy-skate-park_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Corner overlap on left edge
Error: Assertion failed: Corner overlap on left edge
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/assert/js/assert.js:22:13)
    at Function.Shape.roundedRectangleWithRadii (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/kite/js/Shape.js:2074:13)
    at createButtonShape (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/sun/js/buttons/RectangularButtonView.js:227:16)
    at ComboBoxButton.RectangularButtonView [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/sun/js/buttons/RectangularButtonView.js:138:28)
    at new RectangularPushButton (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/sun/js/buttons/RectangularPushButton.js:55:25)
    at new ComboBoxButton (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/sun/js/ComboBoxButton.js:129:5)
    at new ComboBox (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/sun/js/ComboBox.js:116:19)
    at new PhysicalComboBox (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/energy-skate-park/js/energy-skate-park/common/view/PhysicalComboBox.js:85:5)
    at new MassComboBox (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/energy-skate-park/js/energy-skate-park/common/view/MassComboBox.js:57:22)
    at new EnergySkateParkMassControls (https://bayes.colorado.edu/continuous-testing/snapshot-1586164786537/energy-skate-park/js/energy-skate-park/common/view/EnergySkateParkMassControls.js:58:22)
id: Bayes Chrome
Approximately 4/6/2020, 3:19:46 AM
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, tandem names fixed in above commit. But I don't think it is related to the original "index" issue so leaving this open.

**Comment by jessegreenberg** [comment]
I am seeing this in the state wrapper but I am not sure what needs to change. We will revisit this sim for PhET-iO after PhET brand is published, removing my assignment.

**Comment by samreid** [comment]
Marking for https://github.com/phetsims/tasks/issues/1035.

**Comment by KatieWoe** [comment]
Not seeing this in CT right now. Closing
