### ISSUE TITLE
CT Energy SkateParkQueryParameters is defined but never used no-unused-vars

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#244]
Impacts perennial and basics as well
```
energy-skate-park : build : phet
Failure to grunt snapshot-1584677771993/energy-skate-park:
Running "lint-all" task

/data/share/phet/continuous-testing/snapshot-1584677771993/energy-skate-park/js/energy-skate-park/common/view/EnergySkateParkScreenView.js
  35:8  error  'EnergySkateParkQueryParameters' is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
Fatal error: 1 Lint Errors


Approximately 3/19/2020, 10:16:11 PM
energy-skate-park : build : phet-io
Failure to grunt snapshot-1584677771993-phet-io/energy-skate-park:
Running "lint-all" task

/data/share/phet/continuous-testing/snapshot-1584677771993-phet-io/energy-skate-park/js/energy-skate-park/common/view/EnergySkateParkScreenView.js
  35:8  error  'EnergySkateParkQueryParameters' is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
Fatal error: 1 Lint Errors


Approximately 3/19/2020, 10:16:11 PM
energy-skate-park : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/phet-io-wrappers/state/?sim=energy-skate-park&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Assertion failed: PhET-iO API error:
energySkatePark.introScreen.model.loopTrack.physicalProperty:  6. Any static, registered PhetioObject can never be deregistered.
Error: Assertion failed: PhET-iO API error:
energySkatePark.introScreen.model.loopTrack.physicalProperty:  6. Any static, registered PhetioObject can never be deregistered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/assert/js/assert.js?bust=1584691042397:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onPhetioObjectRemoved (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/tandem/js/phetioAPIValidation.js:160:12)
    at PhetioEngine.phetioObjectRemoved (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/phet-io/js/phetioEngine.js:492:25)
    at Object.removePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/phet-io/js/phetioEngine.js:537:52)
    at Tandem.removePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/tandem/js/Tandem.js:169:38)
    at BooleanProperty.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/tandem/js/PhetioObject.js:557:19)
    at BooleanProperty.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/axon/js/Property.js:451:11)
    at BooleanProperty.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/tandem/js/PhetioObject.js:199:20)
    at Track.disposeTrack (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/energy-skate-park/js/energy-skate-park/common/model/Track.js:192:29)
id: Bayes Chrome
Approximately 3/19/2020, 10:16:11 PM
energy-skate-park : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/phet-io-wrappers/state/?sim=energy-skate-park&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: mismatched index, possible start/end mismatch
Error: Assertion failed: mismatched index, possible start/end mismatch
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/assert/js/assert.js?bust=1584691042397:22:13)
    at DataStream.end (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/phet-io/js/dataStream.js:267:15)
    at PhetioCommandProcessor.phetioEndEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/tandem/js/PhetioObject.js:421:30)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/phet-io/js/phetioCommandProcessor.js:107:18
id: Bayes Chrome
Approximately 3/19/2020, 10:16:11 PM
energy-skate-park : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/phet-io-wrappers/state/?sim=energy-skate-park&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Assertion failed: PhET-iO API error:
energySkatePark.introScreen.model.loopTrack.physicalProperty:  6. Any static, registered PhetioObject can never be deregistered.
Error: Assertion failed: PhET-iO API error:
energySkatePark.introScreen.model.loopTrack.physicalProperty:  6. Any static, registered PhetioObject can never be deregistered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/assert/js/assert.js?bust=1584701930557:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onPhetioObjectRemoved (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/tandem/js/phetioAPIValidation.js:160:12)
    at PhetioEngine.phetioObjectRemoved (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/phet-io/js/phetioEngine.js:492:25)
    at Object.removePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/phet-io/js/phetioEngine.js:537:52)
    at Tandem.removePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/tandem/js/Tandem.js:169:38)
    at BooleanProperty.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/tandem/js/PhetioObject.js:557:19)
    at BooleanProperty.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/axon/js/Property.js:451:11)
    at BooleanProperty.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/tandem/js/PhetioObject.js:199:20)
    at Track.disposeTrack (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/energy-skate-park/js/energy-skate-park/common/model/Track.js:192:29)
id: Bayes Chrome
Approximately 3/19/2020, 10:16:11 PM
energy-skate-park : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/phet-io-wrappers/state/?sim=energy-skate-park&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: mismatched index, possible start/end mismatch
Error: Assertion failed: mismatched index, possible start/end mismatch
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/assert/js/assert.js?bust=1584701930557:22:13)
    at DataStream.end (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/phet-io/js/dataStream.js:267:15)
    at PhetioCommandProcessor.phetioEndEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/tandem/js/PhetioObject.js:421:30)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/phet-io/js/phetioCommandProcessor.js:107:18
id: Bayes Chrome
Approximately 3/19/2020, 10:16:11 PM
energy-skate-park : phet-io-tests : assert
https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/phet-io-wrappers/phet-io-wrappers-tests.html?sim=energy-skate-park&phetioDebug
9 out of 9 tests passed. 0 failed.

Approximately 3/19/2020, 10:16:11 PM
energy-skate-park : phet-io-tests : no-assert
https://bayes.colorado.edu/continuous-testing/snapshot-1584677771993/phet-io-wrappers/phet-io-wrappers-tests.html?sim=energy-skate-park
9 out of 9 tests passed. 0 failed.

Approximately 3/19/2020, 10:16:11 PM
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, sorry this was fixed earlier today and should be resolved in future CT iterations.
