### ISSUE TITLE
CT All non-dynamic schema entries must be registered

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#266]
```
energy-skate-park-basics : phet-io-fuzz : require.js
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/energy-skate-park-basics/energy-skate-park-basics_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
energySkateParkBasics.frictionScreen.view.introScreenView.gridNode:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
energySkateParkBasics.frictionScreen.view.introScreenView.gridNode:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/tandem/js/phetioAPIValidation.js:107:16)
    at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/axon/js/TinyEmitter.js:69:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/axon/js/Property.js:270:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/axon/js/Property.js:170:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/axon/js/Property.js:340:32)
    at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/joist/js/Sim.js:851:57
id: Bayes Chrome

energy-skate-park-basics : phet-io-mirror-inputs-fuzz : require.js
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/phet-io-wrappers/mirror-inputs/?sim=energy-skate-park-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
energySkateParkBasics.frictionScreen.view.introScreenView.gridNode:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
energySkateParkBasics.frictionScreen.view.introScreenView.gridNode:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/tandem/js/phetioAPIValidation.js:107:16)
    at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/axon/js/TinyEmitter.js:69:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/axon/js/Property.js:270:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/axon/js/Property.js:170:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/axon/js/Property.js:340:32)
    at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/joist/js/Sim.js:851:57
id: Bayes Chrome

energy-skate-park-basics : phet-io-state-fuzz : require.js
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/phet-io-wrappers/state/?sim=energy-skate-park-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
energySkateParkBasics.frictionScreen.view.introScreenView.gridNode:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
energySkateParkBasics.frictionScreen.view.introScreenView.gridNode:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/tandem/js/phetioAPIValidation.js:107:16)
    at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/axon/js/TinyEmitter.js:69:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/axon/js/Property.js:270:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/axon/js/Property.js:170:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/axon/js/Property.js:340:32)
    at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/joist/js/Sim.js:851:57
id: Bayes Chrome

energy-skate-park-basics : phet-io-studio-fuzz : require.js
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/studio/?sim=energy-skate-park-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
energySkateParkBasics.frictionScreen.view.introScreenView.gridNode:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
energySkateParkBasics.frictionScreen.view.introScreenView.gridNode:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/tandem/js/phetioAPIValidation.js:107:16)
    at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/axon/js/TinyEmitter.js:69:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/axon/js/Property.js:270:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/axon/js/Property.js:170:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/axon/js/Property.js:340:32)
    at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587719824647/joist/js/Sim.js:851:57
id: Bayes Chrome
```

**Comment by jessegreenberg** [comment]
Sorry, my fault. Baslines have been updated.
