### ISSUE TITLE
CT cannot read property skaterState of undefined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#272]
```
energy-skate-park : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/energy-skate-park/build/phet/energy-skate-park_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1593109636208%22%2C%22timestamp%22%3A1593114281910%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'skaterState' of undefined
TypeError: Cannot read property 'skaterState' of undefined
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/energy-skate-park/build/phet/energy-skate-park_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1593109636208%22%2C%22timestamp%22%3A1593114281910%7D&fuzz&memoryLimit=1000:991:1079197)
at Object.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/energy-skate-park/build/phet/energy-skate-park_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1593109636208%22%2C%22timestamp%22%3A1593114281910%7D&fuzz&memoryLimit=1000:991:1672898)
at rP.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/energy-skate-park/build/phet/energy-skate-park_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1593109636208%22%2C%22timestamp%22%3A1593114281910%7D&fuzz&memoryLimit=1000:991:1671527)
at rP.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/energy-skate-park/build/phet/energy-skate-park_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1593109636208%22%2C%22timestamp%22%3A1593114281910%7D&fuzz&memoryLimit=1000:991:629773)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/energy-skate-park/build/phet/energy-skate-park_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1593109636208%22%2C%22timestamp%22%3A1593114281910%7D&fuzz&memoryLimit=1000:991:1111940
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/energy-skate-park/build/phet/energy-skate-park_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1593109636208%22%2C%22timestamp%22%3A1593114281910%7D&fuzz&memoryLimit=1000:991:97319)
at rP.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/energy-skate-park/build/phet/energy-skate-park_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1593109636208%22%2C%22timestamp%22%3A1593114281910%7D&fuzz&memoryLimit=1000:991:1112894)
at rP.pointerMove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/energy-skate-park/build/phet/energy-skate-park_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1593109636208%22%2C%22timestamp%22%3A1593114281910%7D&fuzz&memoryLimit=1000:991:632077)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/energy-skate-park/build/phet/energy-skate-park_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1593109636208%22%2C%22timestamp%22%3A1593114281910%7D&fuzz&memoryLimit=1000:991:551938)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/energy-skate-park/build/phet/energy-skate-park_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1593109636208%22%2C%22timestamp%22%3A1593114281910%7D&fuzz&memoryLimit=1000:991:551630)
id: Bayes Chrome
Snapshot from 6/25/2020, 12:27:16 PM

----------------------------------

energy-skate-park : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/phet-io-wrappers/mirror-inputs/?sim=energy-skate-park&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1593109636208%22%2C%22timestamp%22%3A1593115080737%7D
Uncaught Error: Uncaught Error: Assertion failed: data should exist for the cursor to be draggable
Error: Assertion failed: data should exist for the cursor to be draggable
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/assert/js/assert.js:22:13)
at DragListener.start [as _start] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/griddle/js/XYCursorPlot.js:300:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/scenery/js/listeners/DragListener.js:298:27
at DragListener.onPress (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/scenery/js/listeners/PressListener.js:590:17)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/axon/js/Action.js:225:18)
at DragListener.press (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/scenery/js/listeners/PressListener.js:388:23)
at DragListener.press (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/scenery/js/listeners/DragListener.js:279:51)
at DragListener.tryTouchSnag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/scenery/js/listeners/DragListener.js:382:12)
at DragListener.touchmove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/scenery/js/listeners/DragListener.js:653:10)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/scenery/js/input/Input.js:1847:33)
id: Bayes Chrome
Snapshot from 6/25/2020, 12:27:16 PM

----------------------------------

energy-skate-park : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/studio/?sim=energy-skate-park&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1593109636208%22%2C%22timestamp%22%3A1593122000822%7D
Uncaught Error: Uncaught Error: Assertion failed: data should exist for the cursor to be draggable
Error: Assertion failed: data should exist for the cursor to be draggable
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/assert/js/assert.js:22:13)
at DragListener.start [as _start] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/griddle/js/XYCursorPlot.js:300:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/scenery/js/listeners/DragListener.js:298:27
at DragListener.onPress (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/scenery/js/listeners/PressListener.js:590:17)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/axon/js/Action.js:225:18)
at DragListener.press (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/scenery/js/listeners/PressListener.js:388:23)
at DragListener.press (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/scenery/js/listeners/DragListener.js:279:51)
at DragListener.tryTouchSnag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/scenery/js/listeners/DragListener.js:382:12)
at DragListener.touchenter (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/scenery/js/listeners/DragListener.js:641:10)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593109636208/scenery/js/input/Input.js:1847:33)
id: Bayes Chrome
Snapshot from 6/25/2020, 12:27:16 PM
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, I think this is fixed in the above commit, but not entirely sure. The assertion message I hit was different (earlier) than the one presented here, but think it has been fixed.  This is happening on the graphs screen, and sim is fuzzing locally with ?screens=3 for me, but I will keep this open or a few CT iterations.

**Comment by jessegreenberg** [comment]
OK I just hit this while fuzzing locally.

**Comment by jessegreenberg** [comment]
There is a problem in DynamicSeries from griddle, when we call removePointAtX without redrawing (for performance) we are also not doing other things like hiding the cursor when it is time. So we remove a bunch of data but the cursor remains visible and can still be clicked by the fuzzer.

**Comment by jessegreenberg** [comment]
OK, the issue mentioned in https://github.com/phetsims/energy-skate-park/issues/272#issuecomment-652555360 has been resolved, and I verified that this assertion is not being hit from this case anymore.
