### ISSUE TITLE
CT data should exist for the cursor to be draggable

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#273]
```
energy-skate-park : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/energy-skate-park/energy-skate-park_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1593394194354%22%2C%22timestamp%22%3A1593406980303%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: data should exist for the cursor to be draggable
Error: Assertion failed: data should exist for the cursor to be draggable
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/assert/js/assert.js:22:13)
at DragListener.start [as _start] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/griddle/js/XYCursorPlot.js:300:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/DragListener.js:298:27
at DragListener.onPress (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/PressListener.js:590:17)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/axon/js/Action.js:225:18)
at DragListener.press (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/PressListener.js:388:23)
at DragListener.press (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/DragListener.js:279:51)
at DragListener.tryTouchSnag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/DragListener.js:382:12)
at DragListener.touchmove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/DragListener.js:653:10)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/input/Input.js:1847:33)
id: Bayes Chrome
Snapshot from 6/28/2020, 7:29:54 PM

----------------------------------

energy-skate-park : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/energy-skate-park/energy-skate-park_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1593394194354%22%2C%22timestamp%22%3A1593419567250%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: data should exist for the cursor to be draggable
Error: Assertion failed: data should exist for the cursor to be draggable
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/assert/js/assert.js:22:13)
at DragListener.start [as _start] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/griddle/js/XYCursorPlot.js:300:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/DragListener.js:298:27
at DragListener.onPress (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/PressListener.js:590:17)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/axon/js/Action.js:225:18)
at DragListener.press (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/PressListener.js:388:23)
at DragListener.press (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/DragListener.js:279:51)
at DragListener.tryTouchSnag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/DragListener.js:382:12)
at DragListener.touchmove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/DragListener.js:653:10)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/input/Input.js:1847:33)
id: Bayes Chrome
Snapshot from 6/28/2020, 7:29:54 PM

----------------------------------

energy-skate-park : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/phet-io-wrappers/mirror-inputs/?sim=energy-skate-park&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1593394194354%22%2C%22timestamp%22%3A1593422217203%7D
Uncaught Error: Uncaught Error: Assertion failed: data should exist for the cursor to be draggable
Error: Assertion failed: data should exist for the cursor to be draggable
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/assert/js/assert.js:22:13)
at DragListener.start [as _start] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/griddle/js/XYCursorPlot.js:300:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/DragListener.js:298:27
at DragListener.onPress (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/PressListener.js:590:17)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/axon/js/Action.js:225:18)
at DragListener.press (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/PressListener.js:388:23)
at DragListener.press (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/DragListener.js:279:51)
at DragListener.tryTouchSnag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/DragListener.js:382:12)
at DragListener.touchenter (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/DragListener.js:641:10)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/input/Input.js:1847:33)
id: Bayes Chrome
Snapshot from 6/28/2020, 7:29:54 PM

----------------------------------

energy-skate-park : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/studio/?sim=energy-skate-park&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1593394194354%22%2C%22timestamp%22%3A1593415408117%7D
Uncaught Error: Uncaught Error: Assertion failed: data should exist for the cursor to be draggable
Error: Assertion failed: data should exist for the cursor to be draggable
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/assert/js/assert.js:22:13)
at DragListener.start [as _start] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/griddle/js/XYCursorPlot.js:300:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/DragListener.js:298:27
at DragListener.onPress (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/PressListener.js:590:17)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/axon/js/Action.js:225:18)
at DragListener.press (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/PressListener.js:388:23)
at DragListener.press (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/DragListener.js:279:51)
at DragListener.tryTouchSnag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/DragListener.js:382:12)
at DragListener.touchmove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/DragListener.js:653:10)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/input/Input.js:1847:33)
id: Bayes Chrome
Snapshot from 6/28/2020, 7:29:54 PM

----------------------------------

energy-skate-park : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/energy-skate-park/energy-skate-park_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1593394194354%22%2C%22timestamp%22%3A1593423234227%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: data should exist for the cursor to be draggable
Error: Assertion failed: data should exist for the cursor to be draggable
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/assert/js/assert.js:22:13)
at DragListener.start [as _start] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/griddle/js/XYCursorPlot.js:300:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/DragListener.js:298:27
at DragListener.onPress (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/PressListener.js:590:17)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/axon/js/Action.js:225:18)
at DragListener.press (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/PressListener.js:388:23)
at DragListener.press (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/DragListener.js:279:51)
at DragListener.tryTouchSnag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/DragListener.js:382:12)
at DragListener.touchmove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/listeners/DragListener.js:653:10)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery/js/input/Input.js:1847:33)
id: Bayes Chrome
Snapshot from 6/28/2020, 7:29:54 PM
```

**Comment by jessegreenberg** [comment]
OK, I figured this one out, resolved in #272.
