### ISSUE TITLE
CT cannot read property get of undefined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#283]
```
energy-skate-park : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/build/phet/energy-skate-park_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340539744%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/build/phet/energy-skate-park_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340539744%7D&fuzz&memoryLimit=1000:90:1083134)
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/build/phet/energy-skate-park_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340539744%7D&fuzz&memoryLimit=1000:90:1061178)
at VA.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/build/phet/energy-skate-park_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340539744%7D&fuzz&memoryLimit=1000:90:1012355)
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/build/phet/energy-skate-park_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340539744%7D&fuzz&memoryLimit=1000:90:1061860)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/build/phet/energy-skate-park_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340539744%7D&fuzz&memoryLimit=1000:90:978030
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/build/phet/energy-skate-park_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340539744%7D&fuzz&memoryLimit=1000:90:97394)
at i.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/build/phet/energy-skate-park_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340539744%7D&fuzz&memoryLimit=1000:90:988654)
at i.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/build/phet/energy-skate-park_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340539744%7D&fuzz&memoryLimit=1000:90:988582)
at i.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/build/phet/energy-skate-park_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340539744%7D&fuzz&memoryLimit=1000:90:988443)
id: Bayes Chrome
Snapshot from 7/21/2020, 7:43:39 AM

----------------------------------

energy-skate-park : fuzz : built-phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340613387%7D&fuzz&memoryLimit=1000&phetioStandalone
Query: fuzz&memoryLimit=1000&phetioStandalone
Uncaught TypeError: Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340613387%7D&fuzz&memoryLimit=1000&phetioStandalone:86:1087982)
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340613387%7D&fuzz&memoryLimit=1000&phetioStandalone:86:1066032)
at wy.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340613387%7D&fuzz&memoryLimit=1000&phetioStandalone:86:1017042)
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340613387%7D&fuzz&memoryLimit=1000&phetioStandalone:86:1066714)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340613387%7D&fuzz&memoryLimit=1000&phetioStandalone:86:982648
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340613387%7D&fuzz&memoryLimit=1000&phetioStandalone:86:109357)
at i.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340613387%7D&fuzz&memoryLimit=1000&phetioStandalone:86:993303)
at i.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340613387%7D&fuzz&memoryLimit=1000&phetioStandalone:86:993231)
at i.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340613387%7D&fuzz&memoryLimit=1000&phetioStandalone:86:993092)
id: Bayes Chrome
Snapshot from 7/21/2020, 7:43:39 AM

----------------------------------

energy-skate-park : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/energy-skate-park_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340607155%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined
at IntroModel.stepModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/js/common/model/EnergySkateParkSaveSampleModel.js:169:59)
at IntroModel.constantStep (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/js/common/model/EnergySkateParkModel.js:372:29)
at EventTimer.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/phet-core/js/EventTimer.js:123:12)
at IntroModel.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/js/common/model/EnergySkateParkModel.js:421:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/joist/js/Sim.js:289:20
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Action.js:225:18)
at EnergySkateParkSim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/joist/js/Sim.js:952:31)
at EnergySkateParkSim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/joist/js/Sim.js:942:12)
at EnergySkateParkSim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/joist/js/Sim.js:925:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/joist/js/Sim.js:864:20
id: Bayes Chrome
Snapshot from 7/21/2020, 7:43:39 AM

----------------------------------

energy-skate-park : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/energy-skate-park_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595339761190%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined
at MeasureModel.stepModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/js/common/model/EnergySkateParkSaveSampleModel.js:169:59)
at MeasureModel.constantStep (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/js/common/model/EnergySkateParkModel.js:372:29)
at EventTimer.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/phet-core/js/EventTimer.js:123:12)
at MeasureModel.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/js/common/model/EnergySkateParkModel.js:421:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/joist/js/Sim.js:289:20
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Action.js:225:18)
at EnergySkateParkSim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/joist/js/Sim.js:952:31)
at EnergySkateParkSim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/joist/js/Sim.js:942:12)
at EnergySkateParkSim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/joist/js/Sim.js:925:12)
id: Bayes Chrome
Snapshot from 7/21/2020, 7:43:39 AM

----------------------------------

energy-skate-park : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/phet-io-wrappers/mirror-inputs/?sim=energy-skate-park&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340438063%7D
Uncaught Error: Uncaught TypeError: Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined
at IntroModel.stepModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/js/common/model/EnergySkateParkSaveSampleModel.js:169:59)
at IntroModel.constantStep (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/js/common/model/EnergySkateParkModel.js:372:29)
at EventTimer.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/phet-core/js/EventTimer.js:123:12)
at IntroModel.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/js/common/model/EnergySkateParkModel.js:421:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/joist/js/Sim.js:289:20
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Action.js:225:18)
at EnergySkateParkSim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/joist/js/Sim.js:952:31)
at EnergySkateParkSim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/joist/js/Sim.js:942:12)
at EnergySkateParkSim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/joist/js/Sim.js:925:12)
id: Bayes Chrome
Snapshot from 7/21/2020, 7:43:39 AM

----------------------------------

energy-skate-park : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/studio/?sim=energy-skate-park&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340872230%7D
Uncaught Error: Uncaught TypeError: Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined
at IntroModel.stepModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/js/common/model/EnergySkateParkSaveSampleModel.js:169:59)
at IntroModel.constantStep (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/js/common/model/EnergySkateParkModel.js:372:29)
at EventTimer.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/phet-core/js/EventTimer.js:123:12)
at IntroModel.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/energy-skate-park/js/common/model/EnergySkateParkModel.js:421:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/joist/js/Sim.js:289:20
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Action.js:225:18)
at EnergySkateParkSim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/joist/js/Sim.js:952:31)
at EnergySkateParkSim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/joist/js/Sim.js:942:12)
at EnergySkateParkSim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/joist/js/Sim.js:925:12)
id: Bayes Chrome
Snapshot from 7/21/2020, 7:43:39 AM
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, sorry- this has been fixed.
