### ISSUE TITLE
CT object is not compatible with merge

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#289]
```
energy-skate-park : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/energy-skate-park_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599646300680%22%2C%22timestamp%22%3A1599648042638%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: object is not compatible with merge
Error: Assertion failed: object is not compatible with merge
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/assert/js/assert.js:22:13)
at assertIsMergeable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:59:3)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:31:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/sherpa/lib/lodash-4.17.4.js:9359:14)
at merge (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:29:5)
at new ScrollingChartNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/griddle/js/ScrollingChartNode.js:45:15)
at new XYCursorPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/griddle/js/XYCursorPlot.js:50:5)
at new EnergyPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/js/graphs/view/EnergyPlot.js:63:5)
at new EnergyGraphAccordionBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/js/graphs/view/EnergyGraphAccordionBox.js:86:24)
id: Bayes Chrome
Snapshot from 9/9/2020, 4:11:40 AM

----------------------------------

energy-skate-park : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/energy-skate-park_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599646300680%22%2C%22timestamp%22%3A1599653881975%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: object is not compatible with merge
Error: Assertion failed: object is not compatible with merge
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/assert/js/assert.js:22:13)
at assertIsMergeable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:59:3)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:31:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/sherpa/lib/lodash-4.17.4.js:9359:14)
at merge (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:29:5)
at new ScrollingChartNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/griddle/js/ScrollingChartNode.js:45:15)
at new XYCursorPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/griddle/js/XYCursorPlot.js:50:5)
at new EnergyPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/js/graphs/view/EnergyPlot.js:63:5)
at new EnergyGraphAccordionBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/js/graphs/view/EnergyGraphAccordionBox.js:86:24)
id: Bayes Chrome
Snapshot from 9/9/2020, 4:11:40 AM

----------------------------------

energy-skate-park : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/energy-skate-park_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599646300680%22%2C%22timestamp%22%3A1599647274316%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: object is not compatible with merge
Error: Assertion failed: object is not compatible with merge
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/assert/js/assert.js:22:13)
at assertIsMergeable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:59:3)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:31:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/sherpa/lib/lodash-4.17.4.js:9359:14)
at merge (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:29:5)
at new ScrollingChartNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/griddle/js/ScrollingChartNode.js:45:15)
at new XYCursorPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/griddle/js/XYCursorPlot.js:50:5)
at new EnergyPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/js/graphs/view/EnergyPlot.js:63:5)
at new EnergyGraphAccordionBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/js/graphs/view/EnergyGraphAccordionBox.js:86:24)
id: Bayes Chrome
Snapshot from 9/9/2020, 4:11:40 AM

----------------------------------

energy-skate-park : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/energy-skate-park_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599646300680%22%2C%22timestamp%22%3A1599652957964%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: object is not compatible with merge
Error: Assertion failed: object is not compatible with merge
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/assert/js/assert.js:22:13)
at assertIsMergeable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:59:3)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:31:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/sherpa/lib/lodash-4.17.4.js:9359:14)
at merge (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:29:5)
at new ScrollingChartNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/griddle/js/ScrollingChartNode.js:45:15)
at new XYCursorPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/griddle/js/XYCursorPlot.js:50:5)
at new EnergyPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/js/graphs/view/EnergyPlot.js:63:5)
at new EnergyGraphAccordionBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/js/graphs/view/EnergyGraphAccordionBox.js:86:24)
id: Bayes Chrome
Snapshot from 9/9/2020, 4:11:40 AM

----------------------------------

energy-skate-park : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-io-wrappers/mirror-inputs/?sim=energy-skate-park&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599646300680%22%2C%22timestamp%22%3A1599647680550%7D
Uncaught Error: Uncaught Error: Assertion failed: object is not compatible with merge
Error: Assertion failed: object is not compatible with merge
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/assert/js/assert.js:22:13)
at assertIsMergeable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:59:3)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:31:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/sherpa/lib/lodash-4.17.4.js:9359:14)
at merge (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:29:5)
at new ScrollingChartNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/griddle/js/ScrollingChartNode.js:45:15)
at new XYCursorPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/griddle/js/XYCursorPlot.js:50:5)
at new EnergyPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/js/graphs/view/EnergyPlot.js:63:5)
at new EnergyGraphAccordionBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/js/graphs/view/EnergyGraphAccordionBox.js:86:24)
id: Bayes Chrome
Snapshot from 9/9/2020, 4:11:40 AM

----------------------------------

energy-skate-park : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-io-wrappers/mirror-inputs/?sim=energy-skate-park&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599646300680%22%2C%22timestamp%22%3A1599653212367%7D
Uncaught Error: Uncaught Error: Assertion failed: object is not compatible with merge
Error: Assertion failed: object is not compatible with merge
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/assert/js/assert.js:22:13)
at assertIsMergeable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:59:3)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:31:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/sherpa/lib/lodash-4.17.4.js:9359:14)
at merge (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:29:5)
at new ScrollingChartNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/griddle/js/ScrollingChartNode.js:45:15)
at new XYCursorPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/griddle/js/XYCursorPlot.js:50:5)
at new EnergyPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/js/graphs/view/EnergyPlot.js:63:5)
at new EnergyGraphAccordionBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/js/graphs/view/EnergyGraphAccordionBox.js:86:24)
id: Bayes Chrome
Snapshot from 9/9/2020, 4:11:40 AM

----------------------------------

energy-skate-park : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/studio/?sim=energy-skate-park&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599646300680%22%2C%22timestamp%22%3A1599648090136%7D
Uncaught Error: Uncaught Error: Assertion failed: object is not compatible with merge
Error: Assertion failed: object is not compatible with merge
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/assert/js/assert.js:22:13)
at assertIsMergeable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:59:3)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:31:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/sherpa/lib/lodash-4.17.4.js:9359:14)
at merge (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:29:5)
at new ScrollingChartNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/griddle/js/ScrollingChartNode.js:45:15)
at new XYCursorPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/griddle/js/XYCursorPlot.js:50:5)
at new EnergyPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/js/graphs/view/EnergyPlot.js:63:5)
at new EnergyGraphAccordionBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/js/graphs/view/EnergyGraphAccordionBox.js:86:24)
id: Bayes Chrome
Snapshot from 9/9/2020, 4:11:40 AM

----------------------------------

energy-skate-park : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/studio/?sim=energy-skate-park&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599646300680%22%2C%22timestamp%22%3A1599653524257%7D
Uncaught Error: Uncaught Error: Assertion failed: object is not compatible with merge
Error: Assertion failed: object is not compatible with merge
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/assert/js/assert.js:22:13)
at assertIsMergeable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:59:3)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:31:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/sherpa/lib/lodash-4.17.4.js:9359:14)
at merge (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:29:5)
at new ScrollingChartNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/griddle/js/ScrollingChartNode.js:45:15)
at new XYCursorPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/griddle/js/XYCursorPlot.js:50:5)
at new EnergyPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/js/graphs/view/EnergyPlot.js:63:5)
at new EnergyGraphAccordionBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/js/graphs/view/EnergyGraphAccordionBox.js:86:24)
id: Bayes Chrome
Snapshot from 9/9/2020, 4:11:40 AM

----------------------------------

energy-skate-park : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-io-wrappers/phet-io-wrappers-tests.html?sim=energy-skate-park&phetioDebug
3 out of 4 tests passed. 1 failed.
SimTests: energy-skate-park: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: object is not compatible with merge
Error: Assertion failed: object is not compatible with merge
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/assert/js/assert.js:22:13)
at assertIsMergeable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:59:3)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:31:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/sherpa/lib/lodash-4.17.4.js:9359:14)
at merge (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:29:5)
at new ScrollingChartNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/griddle/js/ScrollingChartNode.js:45:15)
at new XYCursorPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/griddle/js/XYCursorPlot.js:50:5)
at new EnergyPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/js/graphs/view/EnergyPlot.js:63:5)
at new EnergyGraphAccordionBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/js/graphs/view/EnergyGraphAccordionBox.js:86:24)

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 9/9/2020, 4:11:40 AM

----------------------------------

energy-skate-park : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-io-wrappers/phet-io-wrappers-tests.html?sim=energy-skate-park
3 out of 4 tests passed. 1 failed.
SimTests: energy-skate-park: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: object is not compatible with merge
Error: Assertion failed: object is not compatible with merge
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/assert/js/assert.js:22:13)
at assertIsMergeable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:59:3)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:31:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/sherpa/lib/lodash-4.17.4.js:9359:14)
at merge (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:29:5)
at new ScrollingChartNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/griddle/js/ScrollingChartNode.js:45:15)
at new XYCursorPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/griddle/js/XYCursorPlot.js:50:5)
at new EnergyPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/js/graphs/view/EnergyPlot.js:63:5)
at new EnergyGraphAccordionBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/js/graphs/view/EnergyGraphAccordionBox.js:86:24)

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 9/9/2020, 4:11:40 AM

----------------------------------

energy-skate-park : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/energy-skate-park_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1599646300680%22%2C%22timestamp%22%3A1599649225030%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: object is not compatible with merge
Error: Assertion failed: object is not compatible with merge
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/assert/js/assert.js:22:13)
at assertIsMergeable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:59:3)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:31:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/sherpa/lib/lodash-4.17.4.js:9359:14)
at merge (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:29:5)
at new ScrollingChartNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/griddle/js/ScrollingChartNode.js:45:15)
at new XYCursorPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/griddle/js/XYCursorPlot.js:50:5)
at new EnergyPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/js/graphs/view/EnergyPlot.js:63:5)
at new EnergyGraphAccordionBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/js/graphs/view/EnergyGraphAccordionBox.js:86:24)
id: Bayes Chrome
Snapshot from 9/9/2020, 4:11:40 AM

----------------------------------

energy-skate-park : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/energy-skate-park_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1599646300680%22%2C%22timestamp%22%3A1599654068897%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: object is not compatible with merge
Error: Assertion failed: object is not compatible with merge
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/assert/js/assert.js:22:13)
at assertIsMergeable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:59:3)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:31:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/sherpa/lib/lodash-4.17.4.js:9359:14)
at merge (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/phet-core/js/merge.js:29:5)
at new ScrollingChartNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/griddle/js/ScrollingChartNode.js:45:15)
at new XYCursorPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/griddle/js/XYCursorPlot.js:50:5)
at new EnergyPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/js/graphs/view/EnergyPlot.js:63:5)
at new EnergyGraphAccordionBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599646300680/energy-skate-park/js/graphs/view/EnergyGraphAccordionBox.js:86:24)
id: Bayes Chrome
Snapshot from 9/9/2020, 4:11:40 AM
```

**Comment by jessegreenberg** [comment]
Thank you @KatieWoe - fixed in https://github.com/phetsims/griddle/issues/66.
