### ISSUE TITLE
CT Perennial task failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#290]
```
energy-skate-park : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (energy-skate-park, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 5580ms
>> Unused images module: energy-skate-park/images/skater-icon_png.js
>> Production minification complete: 33809ms (2194594 bytes)
>> Debug minification complete: 0ms (6636716 bytes)
Building brand: phet-io
>> Webpack build complete: 4726ms
>> Unused images module: energy-skate-park/images/skater-icon_png.js
Fatal error: Perennial task failed:
Error: Unable to read "../energy-skate-park/js/energy-skate-park-phet-io-overrides.js" file (Error code: ENOENT).
at Object.util.error (/data/share/phet/continuous-testing/ct-snapshots/1600115536411/chipper/node_modules/grunt-legacy-util/index.js:55:39)
at Object.file.read (/data/share/phet/continuous-testing/ct-snapshots/1600115536411/chipper/node_modules/grunt/lib/grunt/file.js:225:22)
at getPreloads.map.filename (/data/share/phet/continuous-testing/ct-snapshots/1600115536411/chipper/js/grunt/buildRunnable.js:180:69)
at Array.map (<anonymous>:null:null)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1600115536411/chipper/js/grunt/buildRunnable.js:180:41)

Full Error details:
{
"origError": {
"errno": -2,
"syscall": "open",
"code": "ENOENT",
"path": "../energy-skate-park/js/energy-skate-park-phet-io-overrides.js"
}
}
Snapshot from 9/14/2020, 2:32:16 PM
```

**Comment by jessegreenberg** [comment]
I am not sure about this one, but looking at commits I suspect it is from https://github.com/phetsims/phet-io/issues/1672. @samreid can you take a look?

**Comment by samreid** [comment]
Thanks, I committed a proposed fix. It's now working on my localhost, closing.
