### ISSUE TITLE
CT:Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#30]
```
energy-skate-park : phet-io-tests
5 out of 7 tests passed. 2 failed.
SimTests: energy-skate-park: iframe api failed:
No error should occur in setting state: Error: Cannot read property 'map' of undefined
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1540386547334/phet-io-wrappers/js/tests/SimTests.js?bust=1540391522997:127:20)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1540386547334/phet-io-wrappers/common/js/Client.js:316:81)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1540386547334/phet-io-wrappers/common/js/Client.js:353:13)

SimTests: energy-skate-park: event indexing failed:
Uncaught TypeError: Cannot read property 'removeChild' of null
https://bayes.colorado.edu/continuous-testing/snapshot-1540386547334/phet-io-wrappers/js/tests/SimTests.js?bust=1540391522997:34


id: Bayes Chrome
Approximately 10/24/2018, 7:09:07 AM
```

**Comment by samreid** [comment]
@zepumph is working on the problem in https://github.com/phetsims/phet-io-wrappers/issues/188#issuecomment-432771369.  I'll put this on hold until that is resolved.

**Comment by samreid** [comment]
https://github.com/phetsims/phet-io-wrappers/issues/188#issuecomment-432771369 is resolved and I don't recall seeing this issue on CT recently. Closing.
