### ISSUE TITLE
CT item not found in Array

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#314]
Link to https://github.com/phetsims/axon/issues/332
```
energy-skate-park : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607350049271/energy-skate-park/energy-skate-park_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1607350049271%22%2C%22timestamp%22%3A1607351253493%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607350049271/assert/js/assert.js:25:13)
at arrayRemove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607350049271/phet-core/js/arrayRemove.js:19:13)
at Proxy.remove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607350049271/axon/js/createObservableArray.js:345:33)
at EnergySkateParkPlaygroundModel.joinTrackToTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607350049271/energy-skate-park/js/common/model/EnergySkateParkModel.js:1730:17)
at EnergySkateParkPlaygroundModel.joinTracks (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607350049271/energy-skate-park/js/common/model/EnergySkateParkModel.js:1531:10)
at TrackDragHandler.trackDragEnded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607350049271/energy-skate-park/js/common/view/TrackDragHandler.js:226:13)
at TrackDragHandler.handleDragEnd (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607350049271/energy-skate-park/js/common/view/TrackDragHandler.js:74:10)
at end (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607350049271/energy-skate-park/js/common/view/TrackDragHandler.js:31:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607350049271/scenery/js/input/SimpleDragHandler.js:237:24
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607350049271/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 12/7/2020, 7:07:29 AM
```

**Comment by jessegreenberg** [comment]
Thanks for getting this @samreid, since https://github.com/phetsims/energy-skate-park/commit/5863e54eee9739f73ae517a943cb0c7af4887ae8 this isn't in CT and sim has been green for a few days.
