### ISSUE TITLE
CT substantial total energy change after corrections

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#323]
```
energy-skate-park : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620957325909/energy-skate-park/energy-skate-park_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1620957325909%22%2C%22timestamp%22%3A1621005383599%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: substantial total energy change after corrections
Error: Assertion failed: substantial total energy change after corrections
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620957325909/assert/js/assert.js:25:13)
at MeasureModel.correctThermalEnergy (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620957325909/energy-skate-park/js/common/model/EnergySkateParkModel.js:584:15)
at MeasureModel.switchToGround (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620957325909/energy-skate-park/js/common/model/EnergySkateParkModel.js:525:35)
at MeasureModel.stepTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620957325909/energy-skate-park/js/common/model/EnergySkateParkModel.js:1100:23)
at MeasureModel.stepModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620957325909/energy-skate-park/js/common/model/EnergySkateParkModel.js:1460:19)
at MeasureModel.stepModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620957325909/energy-skate-park/js/common/model/EnergySkateParkSaveSampleModel.js:161:32)
at MeasureModel.constantStep (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620957325909/energy-skate-park/js/common/model/EnergySkateParkModel.js:388:29)
at EventTimer.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620957325909/phet-core/js/EventTimer.js:120:12)
at MeasureModel.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620957325909/energy-skate-park/js/common/model/EnergySkateParkModel.js:437:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620957325909/joist/js/Sim.js:287:22
id: Bayes Chrome
Snapshot from 5/13/2021, 7:55:25 PM
```

**Comment by marlitas** [comment]
We added more detail to the related assertion error, and will keep an eye out on CT since this is a rare hit.

**Comment by marlitas** [comment]
The new logging looks like this:
```
Uncaught Error: Assertion failed: substantial total energy change after corrections. skaterTotalEnergy: -6.4853432765756605, correctedTotalEnergy: 0, delta: 6.4853432765756605
```
That seems buggy to me and really strange... I think more investigation is needed.

**Comment by marlitas** [comment]
This is not within the scope of the upcoming character set publication. Marking as deferred.
