### ISSUE TITLE
CT listener not attached to dataSample emitter

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#325]
```
energy-skate-park : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624835575218/energy-skate-park/energy-skate-park_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1624835575218%22%2C%22timestamp%22%3A1624859532366%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: listener not attached to dataSample emitter
Error: Assertion failed: listener not attached to dataSample emitter
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624835575218/assert/js/assert.js:25:13)
at SkaterPathSensorNode.clearDisplay (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624835575218/energy-skate-park/js/measure/view/SkaterPathSensorNode.js:347:15)
at SkaterPathSensorNode.updateSensorDisplay (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624835575218/energy-skate-park/js/measure/view/SkaterPathSensorNode.js:267:12)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624835575218/axon/js/TinyEmitter.js:86:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624835575218/axon/js/Emitter.js:39:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624835575218/axon/js/Action.js:227:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624835575218/axon/js/Emitter.js:64:19)
at Proxy.push (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624835575218/axon/js/createObservableArray.js:275:32)
at Proxy.add (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624835575218/axon/js/createObservableArray.js:340:35)
at MeasureModel.stepModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624835575218/energy-skate-park/js/common/model/EnergySkateParkSaveSampleModel.js:168:26)
id: Bayes Chrome
Snapshot from 6/27/2021, 5:12:55 PM
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe.

I have been fuzzing the sim for about 5 minutes with multitouch on the Screens that have data samples with multitouch and haven't seen this yet.

From the stack trace it happened after clearing the sensor display, Ill try to do multitouch operations that do this.

**Comment by jessegreenberg** [comment]
Perhaps the listener was already removed, or the updateDisplayListener was never assigned to the EnergySkateParkDataSample. Since this seems to be happening very rarely on CT and with local fuzzing I added some more debugging info to find what is happening to add clues for next time it happens.

**Comment by KatieWoe** [comment]
```
energy-skate-park : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648307235988/energy-skate-park/energy-skate-park_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648307235988%22%2C%22timestamp%22%3A1648340699878%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: listener not attached to dataSample emitter,
dataSample: [object Object],
this.inspectedSample: [object Object]
Error: Assertion failed: listener not attached to dataSample emitter,
dataSample: [object Object],
this.inspectedSample: [object Object]
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648307235988/assert/js/assert.js:25:13)
at SkaterPathSensorNode.clearDisplay (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648307235988/chipper/dist/js/energy-skate-park/js/measure/view/SkaterPathSensorNode.js:315:15)
at SkaterPathSensorNode.updateSensorDisplay (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648307235988/chipper/dist/js/energy-skate-park/js/measure/view/SkaterPathSensorNode.js:236:12)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648307235988/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648307235988/chipper/dist/js/axon/js/Emitter.js:47:22)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648307235988/chipper/dist/js/axon/js/createObservableArray.js:298:79
at Array.forEach (<anonymous>)
at Proxy.splice (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648307235988/chipper/dist/js/axon/js/createObservableArray.js:298:21)
at MeasureModel.batchRemoveSamples (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648307235988/chipper/dist/js/energy-skate-park/js/common/model/EnergySkateParkSaveSampleModel.js:121:22)
at MeasureModel.clearEnergyData (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648307235988/chipper/dist/js/energy-skate-park/js/common/model/EnergySkateParkSaveSampleModel.js:103:10)
id: Bayes Chrome
Snapshot from 3/26/2022, 9:07:15 AM

----------------------------------

energy-skate-park : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648307235988/energy-skate-park/energy-skate-park_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648307235988%22%2C%22timestamp%22%3A1648422357132%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: track should be above ground
Error: Assertion failed: track should be above ground
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648307235988/assert/js/assert.js:25:13)
at Track.containControlPointsInAvailableBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648307235988/chipper/dist/js/energy-skate-park/js/common/model/Track.js:914:19)
at boundsListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648307235988/chipper/dist/js/energy-skate-park/js/common/model/Track.js:174:14)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648307235988/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648307235988/chipper/dist/js/axon/js/Property.js:227:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648307235988/chipper/dist/js/axon/js/Property.js:156:14)
at Property.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648307235988/chipper/dist/js/axon/js/Property.js:289:10)
at EnergySkateParkPlaygroundModel.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648307235988/chipper/dist/js/energy-skate-park/js/common/model/EnergySkateParkModel.js:310:39)
at EnergySkateParkPlaygroundModel.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648307235988/chipper/dist/js/energy-skate-park/js/playground/model/EnergySkateParkPlaygroundModel.js:76:11)
at ResetAllButton.options.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648307235988/chipper/dist/js/scenery-phet/js/buttons/ResetAllButton.js:54:7)
id: Bayes Chrome
Snapshot from 3/26/2022, 9:07:15 AM
```

**Comment by marlitas** [comment]
This is not within the scope of the upcoming character set publication. Marking as deferred.
