### ISSUE TITLE
CT track should be above ground

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#329]
Also in basics:
```
energy-skate-park : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634648928056/energy-skate-park/energy-skate-park_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1634648928056%22%2C%22timestamp%22%3A1634653029445%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: track should be above ground
Error: Assertion failed: track should be above ground
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634648928056/assert/js/assert.js:25:13)
at Track.containControlPointsInAvailableBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634648928056/energy-skate-park/js/common/model/Track.js:890:19)
at boundsListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634648928056/energy-skate-park/js/common/model/Track.js:194:14)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634648928056/axon/js/TinyEmitter.js:86:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634648928056/axon/js/Property.js:279:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634648928056/axon/js/Property.js:191:14)
at Property.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634648928056/axon/js/Property.js:342:10)
at EnergySkateParkPlaygroundModel.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634648928056/energy-skate-park/js/common/model/EnergySkateParkModel.js:329:39)
at EnergySkateParkPlaygroundModel.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634648928056/energy-skate-park/js/playground/model/EnergySkateParkPlaygroundModel.js:91:11)
at ResetAllButton.options.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634648928056/scenery-phet/js/buttons/ResetAllButton.js:65:7)
id: Bayes Chrome
Snapshot from 10/19/2021, 7:08:48 AM
```

**Comment by KatieWoe** [comment]
```
energy-skate-park-basics : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/energy-skate-park-basics/energy-skate-park-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647595636252%22%2C%22timestamp%22%3A1647597207929%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: track should be above ground
Error: Assertion failed: track should be above ground
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/assert/js/assert.js:25:13)
at Track.containControlPointsInAvailableBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/energy-skate-park/js/common/model/Track.js:914:19)
at boundsListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/energy-skate-park/js/common/model/Track.js:174:14)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/axon/js/Property.js:227:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/axon/js/Property.js:156:14)
at Property.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/axon/js/Property.js:289:10)
at PlaygroundModel.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/energy-skate-park/js/common/model/EnergySkateParkModel.js:310:39)
at PlaygroundModel.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/energy-skate-park/js/playground/model/EnergySkateParkPlaygroundModel.js:76:11)
at ResetAllButton.options.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/scenery-phet/js/buttons/ResetAllButton.js:54:7)
id: Bayes Chrome
Snapshot from 3/18/2022, 3:27:16 AM

----------------------------------

energy-skate-park-basics : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/phet-io-wrappers/phet-io-wrappers-tests.html?sim=energy-skate-park-basics&phetioDebug
1 out of 2 tests passed. 1 failed.
SimTests: energy-skate-park-basics: iframe API failed:
Uncaught Error: Cannot handle messages until after initialization
Error: Cannot handle messages until after initialization
at PhetioCommandProcessor.sendAPIRequestError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:203:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:66:16

Uncaught Error: Cannot handle messages until after initializationError: Cannot handle messages until after initialization
at PhetioCommandProcessor.sendAPIRequestError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:203:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:66:16
id: Bayes Chrome
Snapshot from 3/18/2022, 3:27:16 AM
```
```
energy-skate-park : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/energy-skate-park/energy-skate-park_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647595636252%22%2C%22timestamp%22%3A1647598957120%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: track should be above ground
Error: Assertion failed: track should be above ground
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/assert/js/assert.js:25:13)
at Track.containControlPointsInAvailableBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/energy-skate-park/js/common/model/Track.js:914:19)
at boundsListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/energy-skate-park/js/common/model/Track.js:174:14)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/axon/js/Property.js:227:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/axon/js/Property.js:156:14)
at Property.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/axon/js/Property.js:289:10)
at EnergySkateParkPlaygroundModel.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/energy-skate-park/js/common/model/EnergySkateParkModel.js:310:39)
at EnergySkateParkPlaygroundModel.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/energy-skate-park/js/playground/model/EnergySkateParkPlaygroundModel.js:76:11)
at ResetAllButton.options.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/scenery-phet/js/buttons/ResetAllButton.js:54:7)
id: Bayes Chrome
Snapshot from 3/18/2022, 3:27:16 AM
```

**Comment by marlitas** [comment]
This is not within the scope of the upcoming character set publication. Marking as deferred.
