### ISSUE TITLE
CT trying to attach tracks, but other track was not found

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#332]
```
energy-skate-park-basics : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637681614091/energy-skate-park-basics/energy-skate-park-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1637681614091%22%2C%22timestamp%22%3A1637683083124%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: trying to attach tracks, but other track was not found
Error: Assertion failed: trying to attach tracks, but other track was not found
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637681614091/assert/js/assert.js:25:13)
at PlaygroundModel.joinTracks (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637681614091/chipper/dist/energy-skate-park/js/common/model/EnergySkateParkModel.js:1343:19)
at TrackDragHandler.trackDragEnded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637681614091/chipper/dist/energy-skate-park/js/common/view/TrackDragHandler.js:188:19)
at TrackDragHandler.handleDragEnd (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637681614091/chipper/dist/energy-skate-park/js/common/view/TrackDragHandler.js:62:14)
at end (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637681614091/chipper/dist/energy-skate-park/js/common/view/TrackDragHandler.js:25:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637681614091/chipper/dist/scenery/js/input/SimpleDragHandler.js:191:34
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637681614091/chipper/dist/axon/js/Action.js:171:22)
at TrackDragHandler.endDrag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637681614091/chipper/dist/scenery/js/input/SimpleDragHandler.js:298:28)
at Object.up (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637681614091/chipper/dist/scenery/js/input/SimpleDragHandler.js:241:26)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637681614091/chipper/dist/scenery/js/input/Input.js:1727:31)
id: Bayes Chrome
Snapshot from 11/23/2021, 8:33:34 AM
```

**Comment by jessegreenberg** [comment]
I am guessing this rare problem is still an issue but it is currently masked by other churn on CT.

**Comment by jessegreenberg** [comment]
This is still happening and I hit it after ~5 minutes of fuzzing with two pointers.

**Comment by marlitas** [comment]
This is not within the scope of the upcoming character set publication, so marking as deferred.
