### ISSUE TITLE
CT Dependencies should be defined, has this Property been disposed?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#336]
Also in basics:
```
energy-skate-park : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/energy-skate-park/energy-skate-park_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652698808733%22%2C%22timestamp%22%3A1652703754612%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Dependencies should be defined, has this Property been disposed?
Error: Assertion failed: Dependencies should be defined, has this Property been disposed?
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/assert/js/assert.js:28:13)
at assert (DerivedProperty.ts:131:14)
at definedDependencies (DerivedProperty.ts:152:56)
at (TinyEmitter.ts:107:42)
at emit (Property.ts:276:22)
at _notifyListeners (Property.ts:208:13)
at set (ButtonModel.ts:188:24)
at listener (TinyEmitter.ts:93:8)
at emit (Property.ts:276:22)
at _notifyListeners (Property.ts:208:13)
id: Bayes Chrome
Snapshot from 5/16/2022, 5:00:08 AM
```

**Comment by jessegreenberg** [comment]
It could be masked by other things but this is not showing up on CT currently. Closing.
