### ISSUE TITLE
CT Cannot read properties of undefined (reading 'typeName')

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#339]
Also in basics:
```
energy-skate-park : fuzz : built-phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1655803244604%22%2C%22timestamp%22%3A1655806752050%7D&fuzz&memoryLimit=1000&phetioStandalone
Query: fuzz&memoryLimit=1000&phetioStandalone
Uncaught TypeError: Cannot read properties of undefined (reading 'typeName')
TypeError: Cannot read properties of undefined (reading 'typeName')
at h (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1655803244604%22%2C%22timestamp%22%3A1655806752050%7D&fuzz&memoryLimit=1000&phetioStandalone:952:1031576)
at Object.getData (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1655803244604%22%2C%22timestamp%22%3A1655806752050%7D&fuzz&memoryLimit=1000&phetioStandalone:952:14587)
at V.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1655803244604%22%2C%22timestamp%22%3A1655806752050%7D&fuzz&memoryLimit=1000&phetioStandalone:952:1013939)
at V._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1655803244604%22%2C%22timestamp%22%3A1655806752050%7D&fuzz&memoryLimit=1000&phetioStandalone:952:14472)
at V.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1655803244604%22%2C%22timestamp%22%3A1655806752050%7D&fuzz&memoryLimit=1000&phetioStandalone:952:14180)
at V.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1655803244604%22%2C%22timestamp%22%3A1655806752050%7D&fuzz&memoryLimit=1000&phetioStandalone:952:19281)
at V.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1655803244604%22%2C%22timestamp%22%3A1655806752050%7D&fuzz&memoryLimit=1000&phetioStandalone:952:19239)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1655803244604%22%2C%22timestamp%22%3A1655806752050%7D&fuzz&memoryLimit=1000&phetioStandalone:952:1962194)
at n.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1655803244604%22%2C%22timestamp%22%3A1655806752050%7D&fuzz&memoryLimit=1000&phetioStandalone:952:20846)
at m._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1655803244604%22%2C%22timestamp%22%3A1655806752050%7D&fuzz&memoryLimit=1000&phetioStandalone:952:14676)
id: Bayes Puppeteer
Snapshot from 6/21/2022, 3:20:44 AM

----------------------------------

energy-skate-park : fuzz : built-phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1655803244604%22%2C%22timestamp%22%3A1655820277967%7D&fuzz&memoryLimit=1000&phetioStandalone
Query: fuzz&memoryLimit=1000&phetioStandalone
Uncaught TypeError: Cannot read properties of undefined (reading 'typeName')
TypeError: Cannot read properties of undefined (reading 'typeName')
at h (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1655803244604%22%2C%22timestamp%22%3A1655820277967%7D&fuzz&memoryLimit=1000&phetioStandalone:952:1031576)
at Object.getData (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1655803244604%22%2C%22timestamp%22%3A1655820277967%7D&fuzz&memoryLimit=1000&phetioStandalone:952:14587)
at V.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1655803244604%22%2C%22timestamp%22%3A1655820277967%7D&fuzz&memoryLimit=1000&phetioStandalone:952:1013939)
at V._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1655803244604%22%2C%22timestamp%22%3A1655820277967%7D&fuzz&memoryLimit=1000&phetioStandalone:952:14472)
at V.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1655803244604%22%2C%22timestamp%22%3A1655820277967%7D&fuzz&memoryLimit=1000&phetioStandalone:952:14180)
at V.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1655803244604%22%2C%22timestamp%22%3A1655820277967%7D&fuzz&memoryLimit=1000&phetioStandalone:952:19281)
at V.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1655803244604%22%2C%22timestamp%22%3A1655820277967%7D&fuzz&memoryLimit=1000&phetioStandalone:952:19239)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1655803244604%22%2C%22timestamp%22%3A1655820277967%7D&fuzz&memoryLimit=1000&phetioStandalone:952:1962194)
at n.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1655803244604%22%2C%22timestamp%22%3A1655820277967%7D&fuzz&memoryLimit=1000&phetioStandalone:952:20846)
at m._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1655803244604%22%2C%22timestamp%22%3A1655820277967%7D&fuzz&memoryLimit=1000&phetioStandalone:952:14676)
id: Bayes Puppeteer
Snapshot from 6/21/2022, 3:20:44 AM

----------------------------------

energy-skate-park : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/energy-skate-park/energy-skate-park_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1655803244604%22%2C%22timestamp%22%3A1655804863703%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: fell back to root serialization state for energySkatePark.general.model.preferencesModel.skaterCharacterSetProperty. Potential solutions:
* mark the type as phetioState: false
* create a custom toStateObject method in your IO Type
* perhaps you have everything right, but forgot to pass in the IOType via phetioType in the constructor
Error: Assertion failed: fell back to root serialization state for energySkatePark.general.model.preferencesModel.skaterCharacterSetProperty. Potential solutions:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/assert/js/assert.js:28:13)
at assert (IOType.ts:531:14)
at toStateObject (IOType.ts:267:31)
at toStateObject (PhetioStateEngine.js:106:48)
at getValueJSON (PhetioStateEngine.js:165:33)
at Array.forEach
at forEach (PhetioStateEngine.js:161:37)
at getState (PhetioStateEngine.js:453:29)
at initialize (phetioEngine.js:250:31)
at listener (TinyEmitter.ts:94:8)
id: Bayes Puppeteer
Snapshot from 6/21/2022, 3:20:44 AM

----------------------------------

energy-skate-park : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/energy-skate-park/energy-skate-park_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1655803244604%22%2C%22timestamp%22%3A1655819123377%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: fell back to root serialization state for energySkatePark.general.model.preferencesModel.skaterCharacterSetProperty. Potential solutions:
* mark the type as phetioState: false
* create a custom toStateObject method in your IO Type
* perhaps you have everything right, but forgot to pass in the IOType via phetioType in the constructor
Error: Assertion failed: fell back to root serialization state for energySkatePark.general.model.preferencesModel.skaterCharacterSetProperty. Potential solutions:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/assert/js/assert.js:28:13)
at assert (IOType.ts:531:14)
at toStateObject (IOType.ts:267:31)
at toStateObject (PhetioStateEngine.js:106:48)
at getValueJSON (PhetioStateEngine.js:165:33)
at Array.forEach
at forEach (PhetioStateEngine.js:161:37)
at getState (PhetioStateEngine.js:453:29)
at initialize (phetioEngine.js:250:31)
at listener (TinyEmitter.ts:94:8)
id: Bayes Puppeteer
Snapshot from 6/21/2022, 3:20:44 AM

----------------------------------

energy-skate-park : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/phet-io-wrappers/phet-io-wrappers-tests.html?sim=energy-skate-park&phetioDebug=true&phetioWrapperDebug=true
27 out of 28 tests passed. 1 failed.
SimTests: energy-skate-park: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: fell back to root serialization state for energySkatePark.general.model.preferencesModel.skaterCharacterSetProperty. Potential solutions:
* mark the type as phetioState: false
* create a custom toStateObject method in your IO Type
* perhaps you have everything right, but forgot to pass in the IOType via phetioType in the constructor
Error: Assertion failed: fell back to root serialization state for energySkatePark.general.model.preferencesModel.skaterCharacterSetProperty. Potential solutions:
* mark the type as phetioState: false
* create a custom toStateObject method in your IO Type
* perhaps you have everything right, but forgot to pass in the IOType via phetioType in the constructor
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/assert/js/assert.js:28:13)
at Object.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/chipper/dist/js/tandem/js/types/IOType.js:449:15)
at IOType.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/chipper/dist/js/tandem/js/types/IOType.js:194:32)
at PhetioStateEngine.getValueJSON (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/chipper/dist/js/phet-io/js/PhetioStateEngine.js:107:49)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/chipper/dist/js/phet-io/js/PhetioStateEngine.js:165:32
at Array.forEach (<anonymous>)
at PhetioStateEngine.getState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/chipper/dist/js/phet-io/js/PhetioStateEngine.js:161:38)
at PhetioStateEngine.initialize (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/chipper/dist/js/phet-io/js/PhetioStateEngine.js:439:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/chipper/dist/js/phet-io/js/phetioEngine.js:238:32
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/chipper/dist/js/axon/js/TinyEmitter.js:68:9)

Uncaught Error: Uncaught Error: Assertion failed: fell back to root serialization state for energySkatePark.general.model.preferencesModel.skaterCharacterSetProperty. Potential solutions:
* mark the type as phetioState: false
* create a custom toStateObject method in your IO Type
* perhaps you have everything right, but forgot to pass in the IOType via phetioType in the constructorError: Assertion failed: fell back to root serialization state for energySkatePark.general.model.preferencesModel.skaterCharacterSetProperty. Potential solutions:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/assert/js/assert.js:28:13)
at assert (IOType.ts:531:14)
at toStateObject (IOType.ts:267:31)
at toStateObject (PhetioStateEngine.js:106:48)
at getValueJSON (PhetioStateEngine.js:165:33)
at Array.forEach
at forEach (PhetioStateEngine.js:161:37)
at getState (PhetioStateEngine.js:453:29)
at initialize (phetioEngine.js:250:31)
at listener (TinyEmitter.ts:94:8)
id: Bayes Puppeteer
Snapshot from 6/21/2022, 3:20:44 AM

----------------------------------

energy-skate-park : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/phet-io-wrappers/phet-io-wrappers-tests.html?sim=energy-skate-park
25 out of 26 tests passed. 1 failed.
SimTests: energy-skate-park: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: fell back to root serialization state for energySkatePark.general.model.preferencesModel.skaterCharacterSetProperty. Potential solutions:
* mark the type as phetioState: false
* create a custom toStateObject method in your IO Type
* perhaps you have everything right, but forgot to pass in the IOType via phetioType in the constructor
Error: Assertion failed: fell back to root serialization state for energySkatePark.general.model.preferencesModel.skaterCharacterSetProperty. Potential solutions:
* mark the type as phetioState: false
* create a custom toStateObject method in your IO Type
* perhaps you have everything right, but forgot to pass in the IOType via phetioType in the constructor
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/assert/js/assert.js:28:13)
at Object.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/chipper/dist/js/tandem/js/types/IOType.js:449:15)
at IOType.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/chipper/dist/js/tandem/js/types/IOType.js:194:32)
at PhetioStateEngine.getValueJSON (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/chipper/dist/js/phet-io/js/PhetioStateEngine.js:107:49)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/chipper/dist/js/phet-io/js/PhetioStateEngine.js:165:32
at Array.forEach (<anonymous>)
at PhetioStateEngine.getState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/chipper/dist/js/phet-io/js/PhetioStateEngine.js:161:38)
at PhetioStateEngine.initialize (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/chipper/dist/js/phet-io/js/PhetioStateEngine.js:439:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/chipper/dist/js/phet-io/js/phetioEngine.js:238:32
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/chipper/dist/js/axon/js/TinyEmitter.js:68:9)

Uncaught Error: Uncaught Error: Assertion failed: fell back to root serialization state for energySkatePark.general.model.preferencesModel.skaterCharacterSetProperty. Potential solutions:
* mark the type as phetioState: false
* create a custom toStateObject method in your IO Type
* perhaps you have everything right, but forgot to pass in the IOType via phetioType in the constructorError: Assertion failed: fell back to root serialization state for energySkatePark.general.model.preferencesModel.skaterCharacterSetProperty. Potential solutions:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655803244604/assert/js/assert.js:28:13)
at assert (IOType.ts:531:14)
at toStateObject (IOType.ts:267:31)
at toStateObject (PhetioStateEngine.js:106:48)
at getValueJSON (PhetioStateEngine.js:165:33)
at Array.forEach
at forEach (PhetioStateEngine.js:161:37)
at getState (PhetioStateEngine.js:453:29)
at initialize (phetioEngine.js:250:31)
at listener (TinyEmitter.ts:94:8)
id: Bayes Puppeteer
Snapshot from 6/21/2022, 3:20:44 AM
```

**Comment by jessegreenberg** [comment]
This can be reproduced by launching the sim in studio, opening the Preferences dialog, and selecting a different skater character set.

**Comment by jessegreenberg** [comment]
I think to fix this I have to address this TODO:
```js
    // Controls the selected SkaterImages.SkaterCharacterSet. A set of characters is selected from Preferences
    // and the actual skater character is chosen from in-screen UI.
    this.skaterCharacterSetProperty = new Property( SkaterImages.CHARACTER_SET_1, {
      tandem: tandem.createTandem( 'skaterCharacterSetProperty' ),

      // TODO: To get it running in Studio, either supply this or create a generalized type for this Property in joist.
      phetioState: false
    } );
```

**Comment by jessegreenberg** [comment]
It seemed best for now to just use a number to indicate a selected character set. Then the sim can map a value to a set of images because there could be any number of images for various character stances/directions/representations.
