### ISSUE TITLE
CT This node is already managed by a layout container

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#346]
Also in Basics
```
energy-skate-park : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665418156212/studio/?sim=energy-skate-park&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1665418156212%22%2C%22timestamp%22%3A1665421804928%7D
Uncaught Error: Uncaught Error: Assertion failed: This node is already managed by a layout container - make sure to wrap it in a Node if DAG, removing it from an old layout container, etc.
Error: Assertion failed: This node is already managed by a layout container - make sure to wrap it in a Node if DAG, removing it from an old layout container, etc.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665418156212/assert/js/assert.js:28:13)
at assert (LayoutConstraint.ts:51:14)
at addNode (FlowConstraint.ts:446:9)
at insertCell (FlowBox.ts:137:21)
at listener (TinyEmitter.ts:95:8)
at emit (Node.ts:873:30)
at insertChild (Node.ts:1081:15)
at setChildren (LayoutNode.ts:61:19)
at setChildren (Node.ts:1108:9)
at (Node.ts:6320:10)
id: Bayes Puppeteer
Snapshot from 10/10/2022, 10:09:16 AM
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, fixed in the above commit.
