### ISSUE TITLE
CT: Component was missing its tandem

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#37]
```
energy-skate-park : phet-io-fuzz : require.js : load
Uncaught Error: Assertion failed: Component was missing its tandem
Error: Assertion failed: Component was missing its tandem
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/assert/js/assert.js:22:13)
    at ButtonNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/tandem/js/PhetioObject.js?bust=1542220477878:134:17)
    at ButtonNode.mutate (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/scenery/js/nodes/Node.js?bust=1542220477878:4990:12)
    at new ButtonNode (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/sun/js/ComboBox.js?bust=1542220477878:635:12)
    at new ComboBox (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/sun/js/ComboBox.js?bust=1542220477878:270:23)
    at new MassComboBox (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/energy-skate-park/js/energy-skate-park/intro/view/MassComboBox.js?bust=1542220477878:52:7)
    at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/energy-skate-park/js/energy-skate-park/intro/view/IntroScreenView.js?bust=1542220477878:33:25)
    at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/energy-skate-park/js/energy-skate-park/intro/IntroScreen.js?bust=1542220477878:39:34)
    at IntroScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/joist/js/Screen.js?bust=1542220477878:251:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/joist/js/Sim.js?bust=1542220477878:780:18)
id: Bayes Chrome
Approximately 11/14/2018, 11:08:19 AM
energy-skate-park : phet-io-fuzz : require.js : run
Uncaught Error: Assertion failed: Component was missing its tandem
Error: Assertion failed: Component was missing its tandem
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/assert/js/assert.js:22:13)
    at ButtonNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/tandem/js/PhetioObject.js?bust=1542220477878:134:17)
    at ButtonNode.mutate (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/scenery/js/nodes/Node.js?bust=1542220477878:4990:12)
    at new ButtonNode (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/sun/js/ComboBox.js?bust=1542220477878:635:12)
    at new ComboBox (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/sun/js/ComboBox.js?bust=1542220477878:270:23)
    at new MassComboBox (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/energy-skate-park/js/energy-skate-park/intro/view/MassComboBox.js?bust=1542220477878:52:7)
    at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/energy-skate-park/js/energy-skate-park/intro/view/IntroScreenView.js?bust=1542220477878:33:25)
    at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/energy-skate-park/js/energy-skate-park/intro/IntroScreen.js?bust=1542220477878:39:34)
    at IntroScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/joist/js/Screen.js?bust=1542220477878:251:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/joist/js/Sim.js?bust=1542220477878:780:18)
id: Bayes Chrome
Approximately 11/14/2018, 11:08:19 AM
```

**Comment by samreid** [comment]
Proposed fix is in https://github.com/phetsims/sun/commit/04ee849a668299ebfea8e4ba53de3c9b27274a0c, thanks!  Closing.
