### ISSUE TITLE
CT: typeName of null and only components that were added should be removed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#43]
```
energy-skate-park : fuzz : built-phet-io : run
Uncaught TypeError: Cannot read property 'typeName' of null
TypeError: Cannot read property 'typeName' of null
    at s.value (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057-phet-io/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1108:159710)
    at Object.removeInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057-phet-io/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1108:159916)
    at e.removeInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057-phet-io/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1108:40630)
    at e.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057-phet-io/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1108:53209)
    at e.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057-phet-io/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1108:192214)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057-phet-io/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1108:228660)
    at e._fireItemRemoved (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057-phet-io/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1108:208631)
    at e.pop (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057-phet-io/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1108:209277)
    at e.clear (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057-phet-io/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1108:209618)
    at e.clearTracks (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057-phet-io/energy-skate-park/build/phet-io/energy-skate-park_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1108:231780)
id: Bayes Chrome
Approximately 12/3/2018, 11:09:04 PM
energy-skate-park : phet-io-fuzz : require.js : run
Uncaught Error: Assertion failed: Only components that were added should be removed
Error: Assertion failed: Only components that were added should be removed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/assert/js/assert.js:22:13)
    at PhetioEngine.removeInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io/js/phetioEngine.js?bust=1543913966258:560:17)
    at Object.removeInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io/js/phetioEngine.js?bust=1543913966258:592:46)
    at Tandem.removeInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/tandem/js/Tandem.js?bust=1543913966258:145:34)
    at Track.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/tandem/js/PhetioObject.js?bust=1543913966258:348:21)
    at Track.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/energy-skate-park/js/energy-skate-park/common/model/Track.js?bust=1543913966258:845:38)
    at Track.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/tandem/js/PhetioObject.js?bust=1543913966258:128:22)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1543913966258:232:13)
    at ObservableArray._fireItemRemoved (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/axon/js/ObservableArray.js?bust=1543913966258:162:18)
    at ObservableArray.pop (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/axon/js/ObservableArray.js?bust=1543913966258:243:14)
id: Bayes Chrome
Approximately 12/3/2018, 11:09:04 PM
energy-skate-park : phet-io-fuzz : require.js : run
Uncaught Error: Assertion failed: Only components that were added should be removed
Error: Assertion failed: Only components that were added should be removed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/assert/js/assert.js:22:13)
    at PhetioEngine.removeInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io/js/phetioEngine.js?bust=1543924840484:560:17)
    at Object.removeInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io/js/phetioEngine.js?bust=1543924840484:592:46)
    at Tandem.removeInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/tandem/js/Tandem.js?bust=1543924840484:145:34)
    at Track.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/tandem/js/PhetioObject.js?bust=1543924840484:348:21)
    at Track.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/energy-skate-park/js/energy-skate-park/common/model/Track.js?bust=1543924840484:845:38)
    at Track.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/tandem/js/PhetioObject.js?bust=1543924840484:128:22)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1543924840484:232:13)
    at ObservableArray._fireItemRemoved (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/axon/js/ObservableArray.js?bust=1543924840484:162:18)
    at ObservableArray.remove (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/axon/js/ObservableArray.js?bust=1543924840484:202:14)
id: Bayes Chrome
Approximately 12/3/2018, 11:09:04 PM
energy-skate-park : phet-io-tests : assert
7 out of 7 tests passed. 0 failed.

Approximately 12/3/2018, 11:09:04 PM
energy-skate-park : phet-io-tests : no-assert
7 out of 7 tests passed. 0 failed.

Approximately 12/3/2018, 11:09:04 PM
```

**Comment by samreid** [comment]
See https://github.com/phetsims/energy-skate-park-basics/issues/446#event-2011263189 for the basics version of the other part.

**Comment by samreid** [comment]
On hold until https://github.com/phetsims/energy-skate-park/issues/6 is addressed.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/energy-skate-park/issues/6 has been addressed.

**Comment by samreid** [comment]
Proposed fixes pushed and fuzzing has gone 60000ms here with no issues, closing for now and will review CT next business day.
