### ISSUE TITLE
CT: assertion during interactWithTracksWhileFalling

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#44]
```
energy-skate-park-basics : fuzz : require.js : run
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544341955175/assert/js/assert.js:22:13)
    at PlaygroundModel.interactWithTracksWhileFalling (https://bayes.colorado.edu/continuous-testing/snapshot-1544341955175/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1544357349833:665:21)
    at PlaygroundModel.stepFreeFall (https://bayes.colorado.edu/continuous-testing/snapshot-1544341955175/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1544357349833:523:23)
    at PlaygroundModel.stepModel (https://bayes.colorado.edu/continuous-testing/snapshot-1544341955175/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1544357349833:1284:69)
    at PlaygroundModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1544341955175/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1544357349833:399:31)
    at Emitter.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1544341955175/joist/js/Sim.js?bust=1544357349833:204:24)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1544341955175/axon/js/Emitter.js?bust=1544357349833:199:53)
    at EnergySkateParkBasicsSim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1544341955175/joist/js/Sim.js?bust=1544357349833:909:34)
    at EnergySkateParkBasicsSim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/snapshot-1544341955175/joist/js/Sim.js?bust=1544357349833:890:14)
    at EnergySkateParkBasicsSim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/snapshot-1544341955175/joist/js/Sim.js?bust=1544357349833:873:14)
id: Bayes Chrome
Approximately 12/9/2018, 12:52:35 AM
```

**Comment by samreid** [comment]
This looks like it is still happening.  This is CT today:

```
energy-skate-park : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1568088970098/assert/js/assert.js:22:13)
    at MeasureModel.interactWithTracksWhileFalling (https://bayes.colorado.edu/continuous-testing/snapshot-1568088970098/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?:717:21)
    at MeasureModel.stepFreeFall (https://bayes.colorado.edu/continuous-testing/snapshot-1568088970098/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?:575:23)
    at MeasureModel.stepModel (https://bayes.colorado.edu/continuous-testing/snapshot-1568088970098/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?:1337:69)
    at MeasureModel.stepModel (https://bayes.colorado.edu/continuous-testing/snapshot-1568088970098/energy-skate-park/js/energy-skate-park/measure/model/MeasureModel.js?:119:79)
    at MeasureModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1568088970098/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?:406:31)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1568088970098/joist/js/Sim.js?:217:22
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1568088970098/axon/js/Action.js?:244:20)
    at EnergySkateParkSim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1568088970098/joist/js/Sim.js?:936:33)
    at EnergySkateParkSim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/snapshot-1568088970098/joist/js/Sim.js?:917:14)
id: Bayes Chrome
Approximately 9/9/2019, 10:16:10 PM
```

**Comment by samreid** [comment]
Co-assigning @jessegreenberg in case he has ideas or gets to it first.

**Comment by jessegreenberg** [comment]
Ran fuzzing during a meeting and hit this after 53 minutes! We are hitting this assertion:
```js
        if ( newThermalEnergy < skaterState.thermalEnergy ) {
          newThermalEnergy = skaterState.thermalEnergy;
          newKineticEnergy = initialEnergy - newPotentialEnergy - newThermalEnergy;

          assert && assert( newKineticEnergy >= 0 );
          if ( newKineticEnergy < 0 ) {
            newKineticEnergy = 0;
          }

          // ke = 1/2 m v v
          newSpeed = Math.sqrt( 2 * newKineticEnergy / skaterState.mass );
          newVelocity = segment.times( newSpeed );
        }
```
`newKineticEnergy` is -3.567377770963276e-7.

**Comment by jessegreenberg** [comment]
Without fuzzing, when the skater is dropped over the track
`newPotentialEnergy - skaterState.getPotentialEnergy()` returns a nevative value. So I think the correction doesn't work correctly when the skater is bumped up and potential energy increases.

**Comment by jessegreenberg** [comment]
I found the case where skater in freefall can be bumped up to cross a track:
![image](https://user-images.githubusercontent.com/6396244/64633038-643ab600-d3c8-11e9-9e65-ef8a7ae09553.png)

**Comment by jessegreenberg** [comment]
With the above case, I am not able to create a case where newThermalEnergy < skaterState.thermalEnergy. I tried `phet.chipper.makeRandomSlowness()` (recommended in https://github.com/phetsims/energy-skate-park-basics/issues/141 to reproduce), but I am still not seeing it.

**Comment by jessegreenberg** [comment]
This correction was originally added in https://github.com/phetsims/energy-skate-park-basics/commit/11a1a1d1cf3c03cd80f2608500818a7817d93468 and at that time the correction occured if `if ( newThermalEnergy < 0 ) ` which matches the comment. NOW the correction is         if ( `newThermalEnergy < skaterState.thermalEnergy ) {`. I want to see why that changed.

**Comment by jessegreenberg** [comment]
Just hit this with the following track while fuzzing
![image](https://user-images.githubusercontent.com/6396244/70837755-1ff9f000-1dd3-11ea-936c-a8e7e4df63b2.png)

**Comment by jessegreenberg** [comment]
Every time I have seen this  newPotentialEnergy ~= initialEnergy, within the realm of precision error. Certainly these are values that would not be observable by the user. See above values. When we hit this assertion we have determined that we cannot pull energy from thermal or kinetic energy. So I recommend that we just allow the energy loss from the system and reduce from total energy.

IF this ever occurs outside of fuzz testing (which we have never been able to produce) then the energy loss will be small enough that it is not perceptible to the user.

**Comment by jessegreenberg** [comment]
Proposed change in the above commit. This error has appeared twice in the last two days. I replaced teh existing assertion with a new one
>             assert && assert( Util.equalsEpsilon( newTotalEnergy, initialEnergy, 1E-8 ), 'substantial total energy change after corrections' );

1E-8 is used throughout to ensure conservation of energy in the limit of computational precision.
I will wait to see if this new assertion appears before closing, will give CT a few days.

**Comment by jessegreenberg** [comment]
It appears that the correction used here may also resolve #45. https://github.com/phetsims/energy-skate-park/commit/b81ff3226aac21fd6055606ed6e61b91d3af7639 was generalized to apply to both cases. Ill be watching CT.

**Comment by jessegreenberg** [comment]
Yes, it seems so, closing this one.
