### ISSUE TITLE
CT issues related to Phet-iO

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#57]
I noticed a number of CT errors in this sim and basics. Probably due to usage of NumberDisplay, but maybe something else. Ill take a look.

**Comment by jessegreenberg** [comment]
Here is the issue, caught in wrapper unit tests:
> Uncaught Error: Uncaught Error: Assertion failed: Only instrumented instances can emit to the data stream. Has it been disposed? energySkatePark.labScreen.labScreenView.graphsScreenView.trackNode.track_2.controlPointNode1.inputListener.dragEndedEmitter.emitted

**Comment by KatieWoe** [comment]
Here are a number of issues I saw, that may be related.  Let me know if they aren't and need a different issue @jessegreenberg 
```
energy-skate-park : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Assertion failed: value is out of range, value=0.2, range=[5,100]
Error: Assertion failed: value is out of range, value=0.2, range=[5,100]
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/assert/js/assert.js:22:13)
    at NumberProperty.assertNumberPropertyValidateValue.value [as assertNumberPropertyValidateValue] (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/axon/js/NumberProperty.js?bust=1549374834368:60:26)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/axon/js/NumberProperty.js?bust=1549374834368:83:54)
    at NumberProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/axon/js/Property.js?bust=1549374834368:308:34)
    at before (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/sun/js/ComboBoxListBox.js?bust=1549374834368:77:26)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/axon/js/Emitter.js?bust=1549374834368:201:34)
    at Object.up (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/sun/js/ComboBoxListBox.js?bust=1549374834368:94:24)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/Input.js?bust=1549374834368:1799:27)
    at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/Input.js?bust=1549374834368:1829:14)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/Input.js?bust=1549374834368:1759:12)
id: Bayes Chrome
Approximately 2/5/2019, 12:29:16 AM
energy-skate-park : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Only instrumented instances can emit to the data stream. Has it been disposed? energySkatePark.labScreen.labScreenView.graphsScreenView.trackNode.track_14.trackDragHandler.inputListener.dragEndedEmitter.emitted
Error: Assertion failed: Only instrumented instances can emit to the data stream. Has it been disposed? energySkatePark.labScreen.labScreenView.graphsScreenView.trackNode.track_14.trackDragHandler.inputListener.dragEndedEmitter.emitted
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/assert/js/assert.js:22:13)
    at Object.start (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io/js/dataStream.js?bust=1549354929875:148:19)
    at Emitter.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/tandem/js/PhetioObject.js?bust=1549354929875:265:50)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/axon/js/Emitter.js?bust=1549354929875:218:14)
    at TrackDragHandler.endDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/SimpleDragHandler.js?bust=1549354929875:328:29)
    at Object.up (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/SimpleDragHandler.js?bust=1549354929875:271:16)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/Input.js?bust=1549354929875:1799:27)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/Input.js?bust=1549354929875:1755:12)
    at Input.upEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/Input.js?bust=1549354929875:1516:12)
    at before (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/Input.js?bust=1549354929875:406:18)
id: Bayes Chrome
Approximately 2/5/2019, 12:29:16 AM
energy-skate-park : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Only instrumented instances can emit to the data stream. Has it been disposed? energySkatePark.labScreen.labScreenView.graphsScreenView.trackNode.track_29.trackDragHandler.inputListener.dragEndedEmitter.emitted
Error: Assertion failed: Only instrumented instances can emit to the data stream. Has it been disposed? energySkatePark.labScreen.labScreenView.graphsScreenView.trackNode.track_29.trackDragHandler.inputListener.dragEndedEmitter.emitted
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/assert/js/assert.js:22:13)
    at Object.start (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io/js/dataStream.js?bust=1549373795390:148:19)
    at Emitter.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/tandem/js/PhetioObject.js?bust=1549373795390:265:50)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/axon/js/Emitter.js?bust=1549373795390:218:14)
    at TrackDragHandler.endDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/SimpleDragHandler.js?bust=1549373795390:328:29)
    at Object.up (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/SimpleDragHandler.js?bust=1549373795390:271:16)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/Input.js?bust=1549373795390:1799:27)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/Input.js?bust=1549373795390:1755:12)
    at Input.upEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/Input.js?bust=1549373795390:1516:12)
    at before (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/Input.js?bust=1549373795390:406:18)
id: Bayes Chrome
Approximately 2/5/2019, 12:29:16 AM
energy-skate-park : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Only instrumented instances can emit to the data stream. Has it been disposed? energySkatePark.labScreen.labScreenView.graphsScreenView.trackNode.track_8.controlPointNode1.inputListener.dragEndedEmitter.emitted
Error: Assertion failed: Only instrumented instances can emit to the data stream. Has it been disposed? energySkatePark.labScreen.labScreenView.graphsScreenView.trackNode.track_8.controlPointNode1.inputListener.dragEndedEmitter.emitted
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/assert/js/assert.js:22:13)
    at Object.start (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io/js/dataStream.js?bust=1549382035660:148:19)
    at Emitter.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/tandem/js/PhetioObject.js?bust=1549382035660:265:50)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/axon/js/Emitter.js?bust=1549382035660:218:14)
    at SimpleDragHandler.endDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/SimpleDragHandler.js?bust=1549382035660:328:29)
    at Object.up (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/SimpleDragHandler.js?bust=1549382035660:271:16)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/Input.js?bust=1549382035660:1799:27)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/Input.js?bust=1549382035660:1755:12)
    at Input.upEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/Input.js?bust=1549382035660:1516:12)
    at before (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/Input.js?bust=1549382035660:256:16)
id: Bayes Chrome
Approximately 2/5/2019, 12:29:16 AM
energy-skate-park : phet-io-tests : assert
7 out of 7 tests passed. 0 failed.

Approximately 2/5/2019, 12:29:16 AM
energy-skate-park : phet-io-tests : no-assert
7 out of 7 tests passed. 0 failed.

Approximately 2/5/2019, 12:29:16 AM
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe!

**Comment by jessegreenberg** [comment]
I think the disposal issue is related to https://github.com/phetsims/scenery/issues/928. Ill look into the out of range assertions now too.

**Comment by jessegreenberg** [comment]
Range assertion was caused by 48f1a42cf6bb8e23db5fc7587ff42c58899e25bd, fixed by the above commit. Sim is fuzzing without error and unit tests are passing. Closing.
