### ISSUE TITLE
CT Tandem was required but not supplied

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#70]
```
energy-skate-park : phet-io-fuzz : require.js : load
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/assert/js/assert.js:22:13)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/tandem/js/Tandem.js?bust=1558520663227:105:21)
    at Action.register (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/tandem/js/PhetioObject.js?bust=1558520663227:284:19)
    at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/tandem/js/PhetioObject.js?bust=1558520663227:271:12)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/tandem/js/PhetioObject.js?bust=1558520663227:134:12)
    at new Action (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/axon/js/Action.js?bust=1558520663227:83:7)
    at DragListener.PressListener [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/scenery/js/listeners/PressListener.js?bust=1558520663227:239:25)
    at new DragListener (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/scenery/js/listeners/DragListener.js?bust=1558520663227:144:19)
    at new TestGraph (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/energy-skate-park/js/energy-skate-park/graphs/view/TestGraph.js?bust=1558520663227:67:33)
    at new GraphsScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/energy-skate-park/js/energy-skate-park/graphs/view/GraphsScreenView.js?bust=1558520663227:32:21)
id: Bayes Chrome
Approximately 5/21/2019, 10:26:38 PM
energy-skate-park : phet-io-fuzz : require.js : load
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/assert/js/assert.js:22:13)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/tandem/js/Tandem.js?bust=1558524846865:105:21)
    at Action.register (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/tandem/js/PhetioObject.js?bust=1558524846865:284:19)
    at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/tandem/js/PhetioObject.js?bust=1558524846865:271:12)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/tandem/js/PhetioObject.js?bust=1558524846865:134:12)
    at new Action (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/axon/js/Action.js?bust=1558524846865:83:7)
    at DragListener.PressListener [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/scenery/js/listeners/PressListener.js?bust=1558524846865:239:25)
    at new DragListener (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/scenery/js/listeners/DragListener.js?bust=1558524846865:144:19)
    at new TestGraph (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/energy-skate-park/js/energy-skate-park/graphs/view/TestGraph.js?bust=1558524846865:67:33)
    at new GraphsScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/energy-skate-park/js/energy-skate-park/graphs/view/GraphsScreenView.js?bust=1558524846865:32:21)
id: Bayes Chrome
Approximately 5/21/2019, 10:26:38 PM
energy-skate-park : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/assert/js/assert.js:22:13)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/tandem/js/Tandem.js?bust=1558520663227:105:21)
    at Action.register (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/tandem/js/PhetioObject.js?bust=1558520663227:284:19)
    at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/tandem/js/PhetioObject.js?bust=1558520663227:271:12)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/tandem/js/PhetioObject.js?bust=1558520663227:134:12)
    at new Action (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/axon/js/Action.js?bust=1558520663227:83:7)
    at DragListener.PressListener [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/scenery/js/listeners/PressListener.js?bust=1558520663227:239:25)
    at new DragListener (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/scenery/js/listeners/DragListener.js?bust=1558520663227:144:19)
    at new TestGraph (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/energy-skate-park/js/energy-skate-park/graphs/view/TestGraph.js?bust=1558520663227:67:33)
    at new GraphsScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/energy-skate-park/js/energy-skate-park/graphs/view/GraphsScreenView.js?bust=1558520663227:32:21)
id: Bayes Chrome
Approximately 5/21/2019, 10:26:38 PM
energy-skate-park : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/assert/js/assert.js:22:13)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/tandem/js/Tandem.js?bust=1558524846865:105:21)
    at Action.register (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/tandem/js/PhetioObject.js?bust=1558524846865:284:19)
    at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/tandem/js/PhetioObject.js?bust=1558524846865:271:12)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/tandem/js/PhetioObject.js?bust=1558524846865:134:12)
    at new Action (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/axon/js/Action.js?bust=1558524846865:83:7)
    at DragListener.PressListener [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/scenery/js/listeners/PressListener.js?bust=1558524846865:239:25)
    at new DragListener (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/scenery/js/listeners/DragListener.js?bust=1558524846865:144:19)
    at new TestGraph (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/energy-skate-park/js/energy-skate-park/graphs/view/TestGraph.js?bust=1558524846865:67:33)
    at new GraphsScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1558499198844/energy-skate-park/js/energy-skate-park/graphs/view/GraphsScreenView.js?bust=1558524846865:32:21)
id: Bayes Chrome
Approximately 5/21/2019, 10:26:38 PM
energy-skate-park : phet-io-tests : assert
8 out of 8 tests passed. 0 failed.

Approximately 5/21/2019, 10:26:38 PM
energy-skate-park : phet-io-tests : no-assert
8 out of 8 tests passed. 0 failed.

Approximately 5/21/2019, 10:26:38 PM
```

**Comment by jessegreenberg** [comment]
Thanks, fixed above.
