### ISSUE TITLE
CT Thermal energy should be non-negative

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#73]
```
energy-skate-park : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Assertion failed: Thermal energy should be non-negative: skaterState: [object Object], initialEnergy: -0.000023299361984974274, proposedPosition: Vector2(1.6289070876401066, 0), proposedVelocity: Vector2(5.102644642289876e-19, -0.016666666666666666), dt: 0.016666666666666666, newSpeed: 5.102644642289876e-19, newKineticEnergy: 6.834707865691013e-36, newPotentialEnergy: 0, newThermalEnergy: -0.000023299361984974274, referenceHeight: 0, tracked in https://github.com/phetsims/energy-skate-park/issues/45
Error: Assertion failed: Thermal energy should be non-negative: skaterState: [object Object], initialEnergy: -0.000023299361984974274, proposedPosition: Vector2(1.6289070876401066, 0), proposedVelocity: Vector2(5.102644642289876e-19, -0.016666666666666666), dt: 0.016666666666666666, newSpeed: 5.102644642289876e-19, newKineticEnergy: 6.834707865691013e-36, newPotentialEnergy: 0, newThermalEnergy: -0.000023299361984974274, referenceHeight: 0, tracked in https://github.com/phetsims/energy-skate-park/issues/45
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/assert/js/assert.js:22:13)
    at LabModel.switchToGround (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1559496990064:498:17)
    at LabModel.stepFreeFall (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1559496990064:533:21)
    at LabModel.stepTrack (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1559496990064:995:21)
    at LabModel.stepModel (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1559496990064:1305:39)
    at LabModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1559496990064:403:31)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/joist/js/Sim.js?bust=1559496990064:221:22
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/axon/js/Action.js?bust=1559496990064:177:20)
    at EnergySkateParkSim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/joist/js/Sim.js?bust=1559496990064:937:33)
    at EnergySkateParkSim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/joist/js/Sim.js?bust=1559496990064:918:14)
id: Bayes Chrome
Approximately 6/2/2019, 8:28:59 AM
energy-skate-park : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/assert/js/assert.js:22:13)
    at SkaterState.updateThermalEnergy (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/energy-skate-park/js/energy-skate-park/common/model/SkaterState.js?bust=1559507304612:236:17)
    at GraphsModel.stepGround (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1559507304612:469:22)
    at GraphsModel.stepModel (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1559507304612:1303:70)
    at GraphsModel.stepModel (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/energy-skate-park/js/energy-skate-park/graphs/model/GraphsModel.js?bust=1559507304612:56:79)
    at GraphsModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1559507304612:403:31)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/joist/js/Sim.js?bust=1559507304612:221:22
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/axon/js/Action.js?bust=1559507304612:177:20)
    at EnergySkateParkSim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/joist/js/Sim.js?bust=1559507304612:937:33)
    at EnergySkateParkSim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/joist/js/Sim.js?bust=1559507304612:918:14)
id: Bayes Chrome
Approximately 6/2/2019, 8:28:59 AM
energy-skate-park : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/assert/js/assert.js:22:13)
    at SkaterState.updateThermalEnergy (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/energy-skate-park/js/energy-skate-park/common/model/SkaterState.js?bust=1559504142622:236:17)
    at GraphsModel.stepGround (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1559504142622:469:22)
    at GraphsModel.stepModel (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1559504142622:1303:70)
    at GraphsModel.stepModel (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/energy-skate-park/js/energy-skate-park/graphs/model/GraphsModel.js?bust=1559504142622:56:79)
    at GraphsModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1559504142622:403:31)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/joist/js/Sim.js?bust=1559504142622:221:22
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/axon/js/Action.js?bust=1559504142622:177:20)
    at EnergySkateParkSim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/joist/js/Sim.js?bust=1559504142622:937:33)
    at EnergySkateParkSim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/joist/js/Sim.js?bust=1559504142622:918:14)
id: Bayes Chrome
Approximately 6/2/2019, 8:28:59 AM
energy-skate-park : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/assert/js/assert.js:22:13)
    at SkaterState.updateThermalEnergy (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/energy-skate-park/js/energy-skate-park/common/model/SkaterState.js?bust=1559570016992:236:17)
    at GraphsModel.stepGround (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1559570016992:469:22)
    at GraphsModel.stepModel (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1559570016992:1303:70)
    at GraphsModel.stepModel (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/energy-skate-park/js/energy-skate-park/graphs/model/GraphsModel.js?bust=1559570016992:56:79)
    at GraphsModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1559570016992:403:31)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/joist/js/Sim.js?bust=1559570016992:221:22
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/axon/js/Action.js?bust=1559570016992:177:20)
    at EnergySkateParkSim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/joist/js/Sim.js?bust=1559570016992:937:33)
    at EnergySkateParkSim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/snapshot-1559485739184/joist/js/Sim.js?bust=1559570016992:918:14)
id: Bayes Chrome
Approximately 6/2/2019, 8:28:59 AM
energy-skate-park : phet-io-tests : assert
8 out of 8 tests passed. 0 failed.

Approximately 6/2/2019, 8:28:59 AM
energy-skate-park : phet-io-tests : no-assert
8 out of 8 tests passed. 0 failed.

Approximately 6/2/2019, 8:28:59 AM
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, this is  the same as #45, we will discuss there.
