### ISSUE TITLE
CT value not in validValues

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#76]
```
energy-skate-park : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: value not in validValues: 4
Error: Assertion failed: value not in validValues: 4
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/assert/js/assert.js:22:13)
    at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/ValidatorDef.js?bust=1562132741236:220:41)
    at validate (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/validate.js?bust=1562132741236:28:20)
    at Property.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Property.js?bust=1562132741236:84:44)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Property.js?bust=1562132741236:152:29)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/sun/js/buttons/RadioButtonGroupMember.js?bust=1562132741236:125:16
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/TinyEmitter.js?bust=1562132741236:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Emitter.js?bust=1562132741236:46:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Action.js?bust=1562132741236:177:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Emitter.js?bust=1562132741236:71:21)
id: Bayes Chrome
Approximately 7/2/2019, 10:58:52 PM
energy-skate-park : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: value not in validValues: 5
Error: Assertion failed: value not in validValues: 5
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/assert/js/assert.js:22:13)
    at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/ValidatorDef.js?bust=1562156346597:220:41)
    at validate (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/validate.js?bust=1562156346597:28:20)
    at Property.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Property.js?bust=1562156346597:84:44)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Property.js?bust=1562156346597:152:29)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/sun/js/buttons/RadioButtonGroupMember.js?bust=1562156346597:125:16
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/TinyEmitter.js?bust=1562156346597:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Emitter.js?bust=1562156346597:46:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Action.js?bust=1562156346597:177:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Emitter.js?bust=1562156346597:71:21)
id: Bayes Chrome
Approximately 7/2/2019, 10:58:52 PM
energy-skate-park : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: value not in validValues: 4
Error: Assertion failed: value not in validValues: 4
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/assert/js/assert.js:22:13)
    at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/ValidatorDef.js?bust=1562159196041:220:41)
    at validate (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/validate.js?bust=1562159196041:28:20)
    at Property.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Property.js?bust=1562159196041:84:44)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Property.js?bust=1562159196041:152:29)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/sun/js/buttons/RadioButtonGroupMember.js?bust=1562159196041:125:16
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/TinyEmitter.js?bust=1562159196041:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Emitter.js?bust=1562159196041:46:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Action.js?bust=1562159196041:177:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Emitter.js?bust=1562159196041:71:21)
id: Bayes Chrome
Approximately 7/2/2019, 10:58:52 PM
energy-skate-park : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas
Uncaught Error: Assertion failed: value not in validValues: 5
Error: Assertion failed: value not in validValues: 5
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/assert/js/assert.js:22:13)
    at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/ValidatorDef.js?bust=1562139794963:220:41)
    at validate (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/validate.js?bust=1562139794963:28:20)
    at Property.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Property.js?bust=1562139794963:84:44)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Property.js?bust=1562139794963:152:29)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/sun/js/buttons/RadioButtonGroupMember.js?bust=1562139794963:125:16
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/TinyEmitter.js?bust=1562139794963:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Emitter.js?bust=1562139794963:46:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Action.js?bust=1562139794963:177:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Emitter.js?bust=1562139794963:71:21)
id: Bayes Chrome
Approximately 7/2/2019, 10:58:52 PM
energy-skate-park : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas
Uncaught Error: Assertion failed: value not in validValues: 5
Error: Assertion failed: value not in validValues: 5
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/assert/js/assert.js:22:13)
    at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/ValidatorDef.js?bust=1562152087040:220:41)
    at validate (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/validate.js?bust=1562152087040:28:20)
    at Property.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Property.js?bust=1562152087040:84:44)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Property.js?bust=1562152087040:152:29)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/sun/js/buttons/RadioButtonGroupMember.js?bust=1562152087040:125:16
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/TinyEmitter.js?bust=1562152087040:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Emitter.js?bust=1562152087040:46:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Action.js?bust=1562152087040:177:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Emitter.js?bust=1562152087040:71:21)
id: Bayes Chrome
Approximately 7/2/2019, 10:58:52 PM
energy-skate-park : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: value not in validValues: 5
Error: Assertion failed: value not in validValues: 5
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/assert/js/assert.js:22:13)
    at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/ValidatorDef.js?bust=1562142321501:220:41)
    at validate (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/validate.js?bust=1562142321501:28:20)
    at Property.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Property.js?bust=1562142321501:84:44)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Property.js?bust=1562142321501:152:29)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/sun/js/buttons/RadioButtonGroupMember.js?bust=1562142321501:125:16
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/TinyEmitter.js?bust=1562142321501:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Emitter.js?bust=1562142321501:46:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Action.js?bust=1562142321501:177:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Emitter.js?bust=1562142321501:71:21)
id: Bayes Chrome
Approximately 7/2/2019, 10:58:52 PM
energy-skate-park : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: value not in validValues: 4
Error: Assertion failed: value not in validValues: 4
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/assert/js/assert.js:22:13)
    at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/ValidatorDef.js?bust=1562147746143:220:41)
    at validate (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/validate.js?bust=1562147746143:28:20)
    at Property.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Property.js?bust=1562147746143:84:44)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Property.js?bust=1562147746143:152:29)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/sun/js/buttons/RadioButtonGroupMember.js?bust=1562147746143:125:16
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/TinyEmitter.js?bust=1562147746143:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Emitter.js?bust=1562147746143:46:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Action.js?bust=1562147746143:177:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Emitter.js?bust=1562147746143:71:21)
id: Bayes Chrome
Approximately 7/2/2019, 10:58:52 PM
energy-skate-park : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: value not in validValues: 4
Error: Assertion failed: value not in validValues: 4
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/assert/js/assert.js:22:13)
    at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/ValidatorDef.js?bust=1562164468766:220:41)
    at validate (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/validate.js?bust=1562164468766:28:20)
    at Property.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Property.js?bust=1562164468766:84:44)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Property.js?bust=1562164468766:152:29)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/sun/js/buttons/RadioButtonGroupMember.js?bust=1562164468766:125:16
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/TinyEmitter.js?bust=1562164468766:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Emitter.js?bust=1562164468766:46:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Action.js?bust=1562164468766:177:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1562129932630/axon/js/Emitter.js?bust=1562164468766:71:21)
id: Bayes Chrome
Approximately 7/2/2019, 10:58:52 PM
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, fixed.
