### ISSUE TITLE
Uncaught Error: Assertion failed: mismatched messageIndex, possible start/end mismatch

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#8]
Consistently appearing in Bayes CT, all with phet-io fuzzing.

```
energy-skate-park : phet-io-fuzz : require.js : run
Uncaught Error: Assertion failed: mismatched messageIndex, possible start/end mismatch
Error: Assertion failed: mismatched messageIndex, possible start/end mismatch
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1525392864571/assert/js/assert.js:22:13)
    at Object.end (https://bayes.colorado.edu/continuous-testing/snapshot-1525392864571/phet-io/js/phetioEvents.js?bust=1525403441025:178:17)
    at PressListener.endEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1525392864571/tandem/js/PhetioObject.js?bust=1525403441025:201:22)
    at PressListener.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1525392864571/tandem/js/PhetioObject.js?bust=1525403441025:215:14)
    at PressListener.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1525392864571/scenery/js/listeners/PressListener.js?bust=1525403441025:559:38)
    at RoundPushButton.RoundButtonView.disposeRoundButtonView (https://bayes.colorado.edu/continuous-testing/snapshot-1525392864571/sun/js/buttons/RoundButtonView.js?bust=1525403441025:148:21)
    at RoundPushButton.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1525392864571/sun/js/buttons/RoundButtonView.js?bust=1525403441025:488:12)
    at RoundPushButton.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1525392864571/sun/js/buttons/RoundPushButton.js?bust=1525403441025:85:41)
    at RoundPushButton.Node.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1525392864571/scenery/js/nodes/Node.js?bust=1525403441025:495:22)
    at ControlPointUI.disposeControlPointUI (https://bayes.colorado.edu/continuous-testing/snapshot-1525392864571/energy-skate-park/js/energy-skate-park/view/ControlPointUI.js?bust=1525403441025:111:30)
Approximately 5/3/2018, 6:14:24 PM
energy-skate-park : phet-io-fuzz : require.js : run
Uncaught Error: Assertion failed: Exit event not matched by an enter event
Error: Assertion failed: Exit event not matched by an enter event
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1525392864571/assert/js/assert.js:22:13)
    at PressListener.exit (https://bayes.colorado.edu/continuous-testing/snapshot-1525392864571/scenery/js/listeners/PressListener.js?bust=1525403441025:340:17)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1525392864571/scenery/js/input/Input.js?bust=1525403441025:903:72)
    at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/snapshot-1525392864571/scenery/js/input/Input.js?bust=1525403441025:930:14)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1525392864571/scenery/js/input/Input.js?bust=1525403441025:877:12)
    at Input.exitEvents (https://bayes.colorado.edu/continuous-testing/snapshot-1525392864571/scenery/js/input/Input.js?bust=1525403441025:834:16)
    at Input.branchChangeEvents (https://bayes.colorado.edu/continuous-testing/snapshot-1525392864571/scenery/js/input/Input.js?bust=1525403441025:807:14)
    at Input.moveEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1525392864571/scenery/js/input/Input.js?bust=1525403441025:766:26)
    at Input.mouseMove (https://bayes.colorado.edu/continuous-testing/snapshot-1525392864571/scenery/js/input/Input.js?bust=1525403441025:384:12)
    at Display.fuzzMouseEvents (https://bayes.colorado.edu/continuous-testing/snapshot-1525392864571/scenery/js/display/Display.js?bust=1525403441025:1313:23)
Approximately 5/3/2018, 6:14:24 PM
energy-skate-park : phet-io-tests
6 out of 6 tests passed. 0 failed.

Approximately 5/3/2018, 6:14:24 PM
```

**Comment by jessegreenberg** [comment]
This is not showing up on CT, closing.
